# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
sensor: !include sensors.yaml
zone: !include zone.yaml
var: !include variables.yaml

discovery:
  ignore:
    - homekit

#camera:
#  - platform: onvif
#    host: 192.168.1.94
#    port: 554
#    username: admin
#    profile: 2
#    password: !secret camera_yoosee

#sonoffLAN
sonoff:
  username: !secret sonoff_mail
  password: !secret sonoff_pwd
 # reload: always

shell_command:
  reboot_camera_living_room: "curl http://192.168.1.67/cgi-bin/reboot.sh"
  
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

#FOR guest
input_select:
  guests:
    options:
      - home
      - not_home
    initial: not_home
    icon: mdi:guy-fawkes-mask

influxdb:
  host: localhost
  port: 8086
  database: homeassistant
  username: hassio
  password: hassio
  max_retries: 3
  default_measurement: state

#Bluethoot
device_tracker:
  - platform: bluetooth_tracker

# Text to speech
tts:
  - platform: google_translate

system_health:

#shelly_integration
shelly:

webhook:

#termostato
climate:
  - platform: generic_thermostat
    name: Riscaldamento
    heater: switch.thermostat
    target_sensor: sensor.house_temperature
    min_temp: 10
    max_temp: 25
    ac_mode: false
    target_temp: 19.5
    min_cycle_duration:
      seconds: 120
    initial_hvac_mode: "off"
    away_temp: 15



binary_sensor:
  - platform: trend
    sensors:
      bath_humidity:
        entity_id: sensor.multi_sensor_3_3
        sample_duration: 7200
        min_gradient: 0.02
        device_class: moisture
 # - platform: rpi_gpio
 #   bouncetime: 500
 #   ports:
 #     #2: test2 no serigrafia
 #     #3: test3 no serigrafia
 #     4: test4
 #     5: test5     #non collegato
 #     6: test6     #non collegato
 #     #7: test7 no serigrafia
 #     #8: test8 no serigrafia
 #     #9: test9 no serigrafia
 #     #10: test10 no serigrafia
 #     #11: test11 no serigrafia
 #     12: test12
 #     13: test13   #non collegato
 #     #14: test14   no serigrafia
 #     #15: test15 no serigrafia
 #     16: test16
 #     17: test17
 #     18: test18
 #     19: test19   #non collegato
 #     20: test20
 #     21: test21
 #     22: MainBedroomWindow
 #     23: BedroomShield
 #     24: test24
 #     25: test25
 #     26: test26 #non collegato
 #     27: test27

homeassistant:
  packages: !include_dir_named packages
  customize:
    binary_sensor.mainbedroomwindow:
      device_class: opening
    binary_sensor.bedroomshield:
      device_class: opening



yeelight:
  devices:
    192.168.1.64:
      name: entrance
    192.168.1.68:
      name: bagno
    192.168.1.66:
      name: Livingroom

api:

hacs:
  token: !secret token_hacs
  theme: true

frontend:
  themes: !include_dir_merge_named themes

input_datetime:
  livingroom_open:
    has_date: true
    has_time: true
  livingroom_close:
    has_date: true
    has_time: true
  livingroom_lasttime:
    has_time: true
    has_date: false

recorder:
  include:
    domains:
      - sensor
      - switch
  exclude:
    entities:
      - binary_sensor.accensione_carico
#      - binary_sensor.bath_humidity
#      - binary_sensor.m_bathroom
#      - binary_sensor.m_dressing
#      - binary_sensor.ma_2
#      - binary_sensor.ma_3
#      - binary_sensor.ma_one
      - binary_sensor.remote_ui
      - binary_sensor.soglia_180_min
      - binary_sensor.soglia_instantanea
#      - binary_sensor.sonoff_button1
#      - binary_sensor.sonoff_button1_2
#      - binary_sensor.sonoff_switch1
#      - binary_sensor.sonoff_switch1_2
#      - binary_sensor.sonoff_switch2
#      - binary_sensor.tasmota_button1
      - binary_sensor.updater
#      - binary_sensor.w_bathroom
#      - binary_sensor.w_livingroom
#      - binary_sensor.water_sensor
#      - binary_sensor.water_sensor_2
#      - binary_sensor.water_sensor_3
      - sensor.active_kilocalories
      - sensor.active_time
      - sensor.activity
      - sensor.activity_2
      - sensor.activity_stress_duration
      - sensor.average_active_pace
      - sensor.average_active_pace_2
      - sensor.average_spo2
      - sensor.avg_stress_level
      - sensor.awake_duration
#      - sensor.bathroom_humidity_stats
      - sensor.battery_level
      - sensor.battery_level_2
      - sensor.battery_state
      - sensor.battery_state_2
      - sensor.bed_next_alarm
      - sensor.bed_next_reminder
      - sensor.bed_next_timer
      - sensor.bmr_kilocalories
      - sensor.body_battery_charged
      - sensor.body_battery_drained
      - sensor.body_battery_highest
      - sensor.body_battery_lowest
      - sensor.body_battery_most_recent
      - sensor.bssid
      - sensor.bssid_2
      - sensor.burned_kilocalories
      - sensor.connection_type
      - sensor.connection_type_2
#      - sensor.cpu_temperature
      - sensor.current_pow1
      - sensor.current_power
      - sensor.daily_step_goal
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_cloud_coverage_0d
      - sensor.dark_sky_cloud_coverage_0h
      - sensor.dark_sky_cloud_coverage_3h
      - sensor.dark_sky_humidity
      - sensor.dark_sky_humidity_0d
      - sensor.dark_sky_humidity_0h
      - sensor.dark_sky_humidity_3h
      - sensor.dark_sky_icon
      - sensor.dark_sky_icon_0d
      - sensor.dark_sky_icon_0h
      - sensor.dark_sky_icon_3h
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_probability_0d
      - sensor.dark_sky_precip_probability_0h
      - sensor.dark_sky_precip_probability_3h
      - sensor.dark_sky_summary
      - sensor.dark_sky_summary_0d
      - sensor.dark_sky_summary_0h
      - sensor.dark_sky_summary_3h
      - sensor.dark_sky_temperature
      - sensor.dark_sky_temperature_0h
      - sensor.dark_sky_temperature_3h
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_speed_0d
      - sensor.dark_sky_wind_speed_0h
      - sensor.dark_sky_wind_speed_3h
      - sensor.date
      - sensor.date_time
      - sensor.date_time_iso
      - sensor.date_time_utc
      - sensor.daylight
      - sensor.distance
      - sensor.distance_2
      - sensor.echo_dot_di_roberto_next_alarm
      - sensor.echo_dot_di_roberto_next_reminder
      - sensor.echo_dot_di_roberto_next_timer
#      - sensor.energy_spent
      - sensor.esclusione_1
      - sensor.esclusione_2
      - sensor.floors_ascended
      - sensor.floors_ascended_2
      - sensor.floors_ascended_3
      - sensor.floors_ascended_goal
      - sensor.floors_descended
      - sensor.floors_descended_2
      - sensor.floors_descended_3
      - sensor.geocoded_location
      - sensor.geocoded_location_2
      - sensor.hacs
      - sensor.high_stress_duration
#      - sensor.house_temperature
#      - sensor.humidity_25
      - sensor.intensity_goal
      - sensor.internet_time
      - sensor.iphone_di_roberto_battery_state
      - sensor.israel_coronavirus_confirmed
      - sensor.israel_coronavirus_current
      - sensor.israel_coronavirus_deaths
      - sensor.israel_coronavirus_recovered
      - sensor.italy_coronavirus_confirmed
      - sensor.italy_coronavirus_current
      - sensor.italy_coronavirus_deaths
      - sensor.italy_coronavirus_recovered
      - sensor.last_charge_off
      - sensor.last_update_trigger
      - sensor.last_update_trigger_2
      - sensor.latest_spo2
      - sensor.livingroom_open_today
      - sensor.low_stress_duration
      - sensor.lowest_spo2
      - sensor.m_bagno_battery_level
      - sensor.m_dressing_battery_level
#      - sensor.ma_2
      - sensor.ma_2_battery_level
#      - sensor.ma_3
      - sensor.ma_3_battery_level
#      - sensor.ma_one
      - sensor.ma_one_battery_level
      - sensor.max_heart_rate
      - sensor.max_stress_level
      - sensor.medium_stress_duration
      - sensor.min_heart_rate
#      - sensor.multi_sensor
#      - sensor.multi_sensor_2
#      - sensor.multi_sensor_2_2
#      - sensor.multi_sensor_2_3
#      - sensor.multi_sensor_2_4
      - sensor.multi_sensor_2_battery_level
#      - sensor.multi_sensor_3
#      - sensor.multi_sensor_3_2
#      - sensor.multi_sensor_3_3
      - sensor.multi_sensor_3_battery_level
#      - sensor.multi_sensor_4
      - sensor.multi_sensor_battery_level
#      - sensor.potenza_istantanea
      - sensor.power_pow1
      - sensor.pressure_26
      - sensor.rest_stress_duration
      - sensor.resting_heart_rate
      - sensor.riscaldamento_this_week
      - sensor.riscaldamento_today
      - sensor.riscaldamento_yesterday
      - sensor.ritardo_630
      - sensor.ritardo_700
      - sensor.ritardo_730
      - sensor.ritardo_735
      - sensor.ritardo_800
      - sensor.s_livingroom_battery_level
      - sensor.sedentary_time
#      - sensor.shelly_shsw_pm_b901af_current_consumption
      - sensor.shelly_shsw_pm_b901af_total_consumption_attr
#      - sensor.shelly_shsw_pm_b906cb_current_consumption
      - sensor.shelly_shsw_pm_b906cb_total_consumption_attr
#      - sensor.shelly_shsw_pm_b91874_current_consumption
      - sensor.shelly_shsw_pm_b91874_total_consumption_attr
#      - sensor.shelly_shsw_pm_b9273a_current_consumption
      - sensor.shelly_shsw_pm_b9273a_total_consumption_attr
#      - sensor.shelly_shsw_pm_b9841d_current_consumption
      - sensor.shelly_shsw_pm_b9841d_total_consumption_attr
#      - sensor.shelly_shsw_pm_b984a1_current_consumption
      - sensor.shelly_shsw_pm_b984a1_total_consumption_attr
#      - sensor.shelly_shsw_pm_b98576_current_consumption
      - sensor.shelly_shsw_pm_b98576_total_consumption_attr
      - sensor.sim_1
      - sensor.sim_1_2
      - sensor.sleep_duration
      - sensor.sleeping_time
      - sensor.sonoff_status
      - sensor.sonoff_status_2
      - sensor.ssid
      - sensor.ssid_2
      - sensor.steps
      - sensor.steps_2
      - sensor.tamar_s_iphone_battery_state
      - sensor.tamars_macbook_pro_battery_state
      - sensor.tasmota_status
#      - sensor.temperature_24
      - sensor.temperature_24_battery_level
      - sensor.tempo_in_extrasoglia
      - sensor.tempo_superamento_soglia_180_min
      - sensor.this_device_next_alarm
      - sensor.this_device_next_reminder
      - sensor.this_device_next_timer
      - sensor.time
      - sensor.time_date
      - sensor.time_last_motion
      - sensor.time_utc
      - sensor.total_distance_mtr
      - sensor.total_kilocalories
      - sensor.total_steps
      - sensor.total_stress_duration
      - sensor.tr630
      - sensor.tr700
      - sensor.tr730
      - sensor.tr735
      - sensor.tr800
      - sensor.ultimo_carico_spento
      - sensor.ultimo_intervento
      - sensor.uncat_stress_duration
      - sensor.us_coronavirus_confirmed
      - sensor.us_coronavirus_current
      - sensor.us_coronavirus_deaths
      - sensor.us_coronavirus_recovered
      - sensor.value_livingroom_today
      - sensor.voltage_pow1
      - sensor.w_bathroom_battery_level
      - sensor.w_livingroom_battery_level
      - sensor.water_sensor_2_battery_level
      - sensor.water_sensor_3_battery_level
      - sensor.water_sensor_battery_level
      - sensor.when_630
      - sensor.when_700
      - sensor.when_730
      - sensor.when_735
      - sensor.when_800
      - sensor.where_630
      - sensor.where_700
      - sensor.where_730
      - sensor.where_735
      - sensor.where_800
#      - sensor.yicam
      - sensor.db_file_size

history:
  include:
    domains:
      - sensor
      - switch
      - light
  exclude:
    entities:
      - binary_sensor.accensione_carico
#      - binary_sensor.bath_humidity
#      - binary_sensor.m_bathroom
#      - binary_sensor.m_dressing
#      - binary_sensor.ma_2
#      - binary_sensor.ma_3
#      - binary_sensor.ma_one
      - binary_sensor.remote_ui
      - binary_sensor.soglia_180_min
      - binary_sensor.soglia_instantanea
#      - binary_sensor.sonoff_button1
#      - binary_sensor.sonoff_button1_2
#      - binary_sensor.sonoff_switch1
#      - binary_sensor.sonoff_switch1_2
#      - binary_sensor.sonoff_switch2
#      - binary_sensor.tasmota_button1
      - binary_sensor.updater
#      - binary_sensor.w_bathroom
#      - binary_sensor.w_livingroom
#      - binary_sensor.water_sensor
#      - binary_sensor.water_sensor_2
#      - binary_sensor.water_sensor_3
      - sensor.active_kilocalories
      - sensor.active_time
      - sensor.activity
      - sensor.activity_2
      - sensor.activity_stress_duration
      - sensor.average_active_pace
      - sensor.average_active_pace_2
      - sensor.average_spo2
      - sensor.avg_stress_level
      - sensor.awake_duration
#      - sensor.bathroom_humidity_stats
      - sensor.battery_level
      - sensor.battery_level_2
      - sensor.battery_state
      - sensor.battery_state_2
      - sensor.bed_next_alarm
      - sensor.bed_next_reminder
      - sensor.bed_next_timer
      - sensor.bmr_kilocalories
      - sensor.body_battery_charged
      - sensor.body_battery_drained
      - sensor.body_battery_highest
      - sensor.body_battery_lowest
      - sensor.body_battery_most_recent
      - sensor.bssid
      - sensor.bssid_2
      - sensor.burned_kilocalories
      - sensor.connection_type
      - sensor.connection_type_2
#      - sensor.cpu_temperature
      - sensor.current_pow1
      - sensor.current_power
      - sensor.daily_step_goal
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_cloud_coverage_0d
      - sensor.dark_sky_cloud_coverage_0h
      - sensor.dark_sky_cloud_coverage_3h
      - sensor.dark_sky_humidity
      - sensor.dark_sky_humidity_0d
      - sensor.dark_sky_humidity_0h
      - sensor.dark_sky_humidity_3h
      - sensor.dark_sky_icon
      - sensor.dark_sky_icon_0d
      - sensor.dark_sky_icon_0h
      - sensor.dark_sky_icon_3h
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_probability_0d
      - sensor.dark_sky_precip_probability_0h
      - sensor.dark_sky_precip_probability_3h
      - sensor.dark_sky_summary
      - sensor.dark_sky_summary_0d
      - sensor.dark_sky_summary_0h
      - sensor.dark_sky_summary_3h
      - sensor.dark_sky_temperature
      - sensor.dark_sky_temperature_0h
      - sensor.dark_sky_temperature_3h
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_speed_0d
      - sensor.dark_sky_wind_speed_0h
      - sensor.dark_sky_wind_speed_3h
      - sensor.date
      - sensor.date_time
      - sensor.date_time_iso
      - sensor.date_time_utc
      - sensor.daylight
      - sensor.distance
      - sensor.distance_2
      - sensor.echo_dot_di_roberto_next_alarm
      - sensor.echo_dot_di_roberto_next_reminder
      - sensor.echo_dot_di_roberto_next_timer
#      - sensor.energy_spent
      - sensor.esclusione_1
      - sensor.esclusione_2
      - sensor.floors_ascended
      - sensor.floors_ascended_2
      - sensor.floors_ascended_3
      - sensor.floors_ascended_goal
      - sensor.floors_descended
      - sensor.floors_descended_2
      - sensor.floors_descended_3
      - sensor.geocoded_location
      - sensor.geocoded_location_2
      - sensor.hacs
      - sensor.high_stress_duration
#      - sensor.house_temperature
#      - sensor.humidity_25
      - sensor.intensity_goal
      - sensor.internet_time
      - sensor.iphone_di_roberto_battery_state
      - sensor.israel_coronavirus_confirmed
      - sensor.israel_coronavirus_current
      - sensor.israel_coronavirus_deaths
      - sensor.israel_coronavirus_recovered
      - sensor.italy_coronavirus_confirmed
      - sensor.italy_coronavirus_current
      - sensor.italy_coronavirus_deaths
      - sensor.italy_coronavirus_recovered
      - sensor.last_charge_off
      - sensor.last_update_trigger
      - sensor.last_update_trigger_2
      - sensor.latest_spo2
      - sensor.livingroom_open_today
      - sensor.low_stress_duration
      - sensor.lowest_spo2
      - sensor.m_bagno_battery_level
      - sensor.m_dressing_battery_level
#      - sensor.ma_2
      - sensor.ma_2_battery_level
#      - sensor.ma_3
      - sensor.ma_3_battery_level
#      - sensor.ma_one
      - sensor.ma_one_battery_level
      - sensor.max_heart_rate
      - sensor.max_stress_level
      - sensor.medium_stress_duration
      - sensor.min_heart_rate
#      - sensor.multi_sensor
#      - sensor.multi_sensor_2
#      - sensor.multi_sensor_2_2
#      - sensor.multi_sensor_2_3
#      - sensor.multi_sensor_2_4
      - sensor.multi_sensor_2_battery_level
#      - sensor.multi_sensor_3
#      - sensor.multi_sensor_3_2
#      - sensor.multi_sensor_3_3
      - sensor.multi_sensor_3_battery_level
#      - sensor.multi_sensor_4
      - sensor.multi_sensor_battery_level
#      - sensor.potenza_istantanea
      - sensor.power_pow1
      - sensor.pressure_26
      - sensor.rest_stress_duration
      - sensor.resting_heart_rate
      - sensor.riscaldamento_this_week
      - sensor.riscaldamento_today
      - sensor.riscaldamento_yesterday
      - sensor.ritardo_630
      - sensor.ritardo_700
      - sensor.ritardo_730
      - sensor.ritardo_735
      - sensor.ritardo_800
      - sensor.s_livingroom_battery_level
      - sensor.sedentary_time
#      - sensor.shelly_shsw_pm_b901af_current_consumption
      - sensor.shelly_shsw_pm_b901af_total_consumption_attr
#      - sensor.shelly_shsw_pm_b906cb_current_consumption
      - sensor.shelly_shsw_pm_b906cb_total_consumption_attr
#      - sensor.shelly_shsw_pm_b91874_current_consumption
      - sensor.shelly_shsw_pm_b91874_total_consumption_attr
#      - sensor.shelly_shsw_pm_b9273a_current_consumption
      - sensor.shelly_shsw_pm_b9273a_total_consumption_attr
#      - sensor.shelly_shsw_pm_b9841d_current_consumption
      - sensor.shelly_shsw_pm_b9841d_total_consumption_attr
#      - sensor.shelly_shsw_pm_b984a1_current_consumption
      - sensor.shelly_shsw_pm_b984a1_total_consumption_attr
#      - sensor.shelly_shsw_pm_b98576_current_consumption
      - sensor.shelly_shsw_pm_b98576_total_consumption_attr
      - sensor.sim_1
      - sensor.sim_1_2
      - sensor.sleep_duration
      - sensor.sleeping_time
      - sensor.sonoff_status
      - sensor.sonoff_status_2
      - sensor.ssid
      - sensor.ssid_2
      - sensor.steps
      - sensor.steps_2
      - sensor.tamar_s_iphone_battery_state
      - sensor.tamars_macbook_pro_battery_state
      - sensor.tasmota_status
#      - sensor.temperature_24
      - sensor.temperature_24_battery_level
      - sensor.tempo_in_extrasoglia
      - sensor.tempo_superamento_soglia_180_min
      - sensor.this_device_next_alarm
      - sensor.this_device_next_reminder
      - sensor.this_device_next_timer
      - sensor.time
      - sensor.time_date
      - sensor.time_last_motion
      - sensor.time_utc
      - sensor.total_distance_mtr
      - sensor.total_kilocalories
      - sensor.total_steps
      - sensor.total_stress_duration
      - sensor.tr630
      - sensor.tr700
      - sensor.tr730
      - sensor.tr735
      - sensor.tr800
      - sensor.ultimo_carico_spento
      - sensor.ultimo_intervento
      - sensor.uncat_stress_duration
      - sensor.us_coronavirus_confirmed
      - sensor.us_coronavirus_current
      - sensor.us_coronavirus_deaths
      - sensor.us_coronavirus_recovered
      - sensor.value_livingroom_today
      - sensor.voltage_pow1
      - sensor.w_bathroom_battery_level
      - sensor.w_livingroom_battery_level
      - sensor.water_sensor_2_battery_level
      - sensor.water_sensor_3_battery_level
      - sensor.water_sensor_battery_level
      - sensor.when_630
      - sensor.when_700
      - sensor.when_730
      - sensor.when_735
      - sensor.when_800
      - sensor.where_630
      - sensor.where_700
      - sensor.where_730
      - sensor.where_735
      - sensor.where_800
#      - sensor.yicam
      - sensor.db_file_size


