# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

logger:
  default: notset

group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
sensor: !include sensors.yaml
zone: !include zone.yaml
var: !include variables.yaml

discovery:
  ignore:
    - homekit

#camera:
#  - platform: onvif
#    host: 192.168.1.94
#    port: 554
#    username: admin
#    profile: 2
#    password: !secret camera_yoosee

#sonoffLAN
sonoff:
  username: !secret sonoff_mail
  password: !secret sonoff_pwd
  reload: always

yeelight:


shell_command:
  reboot_camera_living_room: "curl http://192.168.1.69/cgi-bin/reboot.sh"

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
#  base_url: !secret url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem


# Example configuration.yaml entry for the Telegram Bot
telegram_bot:
  - platform: polling
    api_key: !secret api_telegram
    allowed_chat_ids:
      - 925364597


# Example configuration.yaml entry for the notifier
notify:
  - name: telegram
    platform: telegram
    chat_id: 925364597


#FOR guest
input_select:
  guests:
    options:
      - home
      - not_home
    initial: not_home
    icon: mdi:guy-fawkes-mask
  termo:
    options:
      - manual
      - crono
    initial: crono

# influxdb:
#   host: localhost
#   port: 8086
#   database: homeassistant
#   username: hassio
#   password: hassio
#   max_retries: 3
#   default_measurement: state

#Bluethoot
#device_tracker:
#  - platform: bluetooth_tracker

# Text to speech
tts:
  - platform: google_translate

system_health:

#shelly_integration
shelly:

webhook:

#termostato
climate:
  - platform: generic_thermostat
    name: Riscaldamento
    heater: switch.sonoff_2
    target_sensor: sensor.house_temperature
    min_temp: 10
    max_temp: 25
    ac_mode: false
    target_temp: 19.5
    cold_tolerance: 0.1
    hot_tolerance : 0.1
    min_cycle_duration:
      seconds: 1200
    initial_hvac_mode: "off"
    away_temp: 15



binary_sensor:
  - platform: trend
    sensors:
      bath_humidity:
        entity_id: sensor.t_bathroom_2
        sample_duration: 7200
        min_gradient: 0.02
        device_class: moisture
 # - platform: rpi_gpio
 #   bouncetime: 500
 #   ports:
 #     #2: test2 no serigrafia
 #     #3: test3 no serigrafia
 #     4: test4
 #     5: test5     #non collegato
 #     6: test6     #non collegato
 #     #7: test7 no serigrafia
 #     #8: test8 no serigrafia
 #     #9: test9 no serigrafia
 #     #10: test10 no serigrafia
 #     #11: test11 no serigrafia
 #     12: test12
 #     13: test13   #non collegato
 #     #14: test14   no serigrafia
 #     #15: test15 no serigrafia
 #     16: test16
 #     17: test17
 #     18: test18
 #     19: test19   #non collegato
 #     20: test20
 #     21: test21
 #     22: MainBedroomWindow
 #     23: BedroomShield
 #     24: test24
 #     25: test25
 #     26: test26 #non collegato
 #     27: test27

homeassistant:
  packages: !include_dir_named packages
  customize:
    switch.sonoff_1000a539ca:
      device_class: lock
    switch.sonoff_1000a54613:
      device_class: light


api:

#hacs:
#  token: !secret token_hacs
#  theme: true

frontend:
  themes: !include_dir_merge_named themes


recorder:
  exclude:
    domains:
      - automations
    entity_globs:
      - sensor.dark_sky*
      - sensor.tim*
      - sensor.date*
      - sensor.tr*
      - sensor.when*
      - sensor.where*
      - sensor.ritardo*
      - sensor.riscaldamento*
      - sensor.pow1*


history:
  exclude:
    domains:
      - automations
    entity_globs:
      - sensor.dark_sky*
      - sensor.tim*
      - sensor.date*
      - sensor.tr*
      - sensor.when*
      - sensor.where*
      - sensor.ritardo*
      - sensor.riscaldamento*
      - sensor.pow1*