# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

discovery:
  ignore:
    - homekit
    
sonoff:
  username: !secret sonoff_mail
  password: !secret sonoff_pwd

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

input_select:
  guests:
    options:
      - home
      - not_home
    initial: not_home
    icon: mdi:guy-fawkes-mask

device_tracker:
  - platform: bluetooth_tracker


# Text to speech
tts:
  - platform: google_translate
  
system_health:

shelly:

webhook:

climate:
  - platform: generic_thermostat
    name: Riscaldamento
    heater: switch.sonoff_2
    target_sensor: sensor.house_temperature
    min_temp: 10
    max_temp: 25
    ac_mode: false
    target_temp: 19.5
    min_cycle_duration:
      seconds: 120
    initial_hvac_mode: "off"
    away_temp: 15


group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
sensor: !include sensors.yaml
zone: !include zone.yaml
var: !include variables.yaml

binary_sensor:
  - platform: trend
    sensors:
      bath_humidity:
        entity_id: sensor.multi_sensor_3_3
        sample_duration: 7200
        min_gradient: 0.02
        device_class: moisture

yeelight:
  devices:
    192.168.1.64:
      name: entrance
    192.168.1.68:
      name: bagno
    192.168.1.66:
      name: Livingroom
  
api:

hacs:
  token: !secret token_hacs
  theme: true

frontend:
  themes: !include_dir_merge_named themes

input_datetime:
  livingroom_open:
    has_date: true
    has_time: true
  livingroom_close:
    has_date: true
    has_time: true
  livingroom_lasttime:
    has_time: true
    has_date: false

recorder:
  exclude:
    entities:
     - sensor.tr800
     - sensor.ritardo_800
     - sensor.where_800
     - sensor.when_800
     - sensor.tr735
     - sensor.ritardo_735
     - sensor.where_735
     - sensor.when_735
     - sensor.tr730
     - sensor.ritardo_730
     - sensor.where_730
     - sensor.when_730
     - sensor.tr700
     - sensor.ritardo_700
     - sensor.where_700
     - sensor.when_700
     - sensor.tr630
     - sensor.ritardo_630
     - sensor.where_630
     - sensor.when_630

history:
  exclude:
    entities:
     - sensor.tr800
     - sensor.ritardo_800
     - sensor.where_800
     - sensor.when_800
     - sensor.tr735
     - sensor.ritardo_735
     - sensor.where_735
     - sensor.when_735
     - sensor.tr730
     - sensor.ritardo_730
     - sensor.where_730
     - sensor.when_730
     - sensor.tr700
     - sensor.ritardo_700
     - sensor.where_700
     - sensor.when_700
     - sensor.tr630
     - sensor.ritardo_630
     - sensor.where_630
     - sensor.when_630