# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
sensor: !include sensors.yaml
zone: !include zone.yaml
var: !include variables.yaml

discovery:
  ignore:
    - homekit

#camera:
#  - platform: onvif
#    host: 192.168.1.94
#    port: 554
#    username: admin
#    profile: 2
#    password: !secret camera_yoosee
  
#sonoffLAN
sonoff:
  username: !secret sonoff_mail
  password: !secret sonoff_pwd
 # reload: always

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

#FOR guest
input_select:
  guests:
    options:
      - home
      - not_home
    initial: not_home
    icon: mdi:guy-fawkes-mask

#influxdb:
#  host: influxdb
#  port: 8086
#  database: homeassistant
#  username: hassio
#  password: hassio
#  max_retries: 3
#  default_measurement: state

#Bluethoot
device_tracker:
  - platform: bluetooth_tracker

# Text to speech
tts:
  - platform: google_translate
  
system_health:

#shelly_integration
shelly:

webhook:

#termostato
climate:
  - platform: generic_thermostat
    name: Riscaldamento
    heater: switch.thermostat
    target_sensor: sensor.house_temperature
    min_temp: 10
    max_temp: 25
    ac_mode: false
    target_temp: 19.5
    min_cycle_duration:
      seconds: 120
    initial_hvac_mode: "off"
    away_temp: 15



binary_sensor:
  - platform: trend
    sensors:
      bath_humidity:
        entity_id: sensor.multi_sensor_3_3
        sample_duration: 7200
        min_gradient: 0.02
        device_class: moisture
 # - platform: rpi_gpio
 #   bouncetime: 500
 #   ports:
 #     #2: test2 no serigrafia
 #     #3: test3 no serigrafia
 #     4: test4
 #     5: test5     #non collegato
 #     6: test6     #non collegato
 #     #7: test7 no serigrafia
 #     #8: test8 no serigrafia
 #     #9: test9 no serigrafia
 #     #10: test10 no serigrafia
 #     #11: test11 no serigrafia
 #     12: test12
 #     13: test13   #non collegato
 #     #14: test14   no serigrafia
 #     #15: test15 no serigrafia
 #     16: test16
 #     17: test17
 #     18: test18
 #     19: test19   #non collegato
 #     20: test20
 #     21: test21
 #     22: MainBedroomWindow
 #     23: BedroomShield
 #     24: test24
 #     25: test25
 #     26: test26 #non collegato
 #     27: test27
    
homeassistant:
  packages: !include_dir_named packages
  customize:
    binary_sensor.mainbedroomwindow:
      device_class: opening
    binary_sensor.bedroomshield:
      device_class: opening
    
 

yeelight:
  devices:
    192.168.1.64:
      name: entrance
    192.168.1.68:
      name: bagno
    192.168.1.66:
      name: Livingroom
  
api:

hacs:
  token: !secret token_hacs
  theme: true

frontend:
  themes: !include_dir_merge_named themes

input_datetime:
  livingroom_open:
    has_date: true
    has_time: true
  livingroom_close:
    has_date: true
    has_time: true
  livingroom_lasttime:
    has_time: true
    has_date: false

recorder:
  exclude:
    entities:
     - sensor.tr800
     - sensor.ritardo_800
     - sensor.where_800
     - sensor.when_800
     - sensor.tr735
     - sensor.ritardo_735
     - sensor.where_735
     - sensor.when_735
     - sensor.tr730
     - sensor.ritardo_730
     - sensor.where_730
     - sensor.when_730
     - sensor.tr700
     - sensor.ritardo_700
     - sensor.where_700
     - sensor.when_700
     - sensor.tr630
     - sensor.ritardo_630
     - sensor.where_630
     - sensor.when_630
     - sensor.shelly_shsw_pm_b984a1_current_consumption
     - sensor.shelly_shsw_pm_b906cb_current_consumption
     - sensor.shelly_shsw_pm_b98576_current_consumption
     - sensor.shelly_shsw_pm_b9273a_current_consumption
     - sensor.shelly_shsw_pm_b901af_current_consumption
     - sensor.shelly_shsw_pm_b9841d_current_consumption
     - binary_sensor.test12
     - binary_sensor.test13
     - binary_sensor.test16
     - binary_sensor.test17
     - binary_sensor.test18
     - binary_sensor.test19
     - binary_sensor.test20
     - binary_sensor.test21
     - binary_sensor.test24
     - binary_sensor.test25
     - binary_sensor.test26
     - binary_sensor.test27
     - binary_sensor.test4
     - binary_sensor.test5
     - binary_sensor.test6
     - sensor.dark_sky_cloud_coverage	
     - sensor.dark_sky_cloud_coverage_0d	
     - sensor.dark_sky_cloud_coverage_0h	
     - sensor.dark_sky_cloud_coverage_3h	
     - sensor.dark_sky_humidity	
     - sensor.dark_sky_humidity_0d
     - sensor.dark_sky_humidity_0h
     - sensor.dark_sky_humidity_3h
     - sensor.dark_sky_icon
     - sensor.dark_sky_icon_0d
     - sensor.dark_sky_icon_0h
     - sensor.dark_sky_icon_3h
     - sensor.dark_sky_precip_probability	
     - sensor.dark_sky_precip_probability_0d	
     - sensor.dark_sky_precip_probability_0h	
     - sensor.dark_sky_precip_probability_3h	
     - sensor.dark_sky_summary	
     - sensor.dark_sky_summary_0d	
     - sensor.dark_sky_summary_0h	
     - sensor.dark_sky_summary_3h	
     - sensor.dark_sky_temperature	
     - sensor.dark_sky_temperature_0h	
     - sensor.dark_sky_temperature_3h	
     - sensor.dark_sky_wind_speed	
     - sensor.dark_sky_wind_speed_0d	
     - sensor.dark_sky_wind_speed_0h	
     - sensor.dark_sky_wind_speed_3h
     - sensor.date
     - sensor.date_time
     - sensor.date_time_iso
     - sensor.date_time_utc	
     - sensor.daylight

history:
  exclude:
    entities:
     - sensor.tr800
     - sensor.ritardo_800
     - sensor.where_800
     - sensor.when_800
     - sensor.tr735
     - sensor.ritardo_735
     - sensor.where_735
     - sensor.when_735
     - sensor.tr730
     - sensor.ritardo_730
     - sensor.where_730
     - sensor.when_730
     - sensor.tr700
     - sensor.ritardo_700
     - sensor.where_700
     - sensor.when_700
     - sensor.tr630
     - sensor.ritardo_630
     - sensor.where_630
     - sensor.when_630
     - sensor.shelly_shsw_pm_b984a1_current_consumption
     - sensor.shelly_shsw_pm_b906cb_current_consumption
     - sensor.shelly_shsw_pm_b98576_current_consumption
     - sensor.shelly_shsw_pm_b9273a_current_consumption
     - sensor.shelly_shsw_pm_b901af_current_consumption
     - sensor.shelly_shsw_pm_b9841d_current_consumption
     - binary_sensor.test12
     - binary_sensor.test13
     - binary_sensor.test16
     - binary_sensor.test17
     - binary_sensor.test18
     - binary_sensor.test19
     - binary_sensor.test20
     - binary_sensor.test21
     - binary_sensor.test24
     - binary_sensor.test25
     - binary_sensor.test26
     - binary_sensor.test27
     - binary_sensor.test4
     - binary_sensor.test5
     - binary_sensor.test6
     - sensor.dark_sky_cloud_coverage	
     - sensor.dark_sky_cloud_coverage_0d	
     - sensor.dark_sky_cloud_coverage_0h	
     - sensor.dark_sky_cloud_coverage_3h	
     - sensor.dark_sky_humidity	
     - sensor.dark_sky_humidity_0d
     - sensor.dark_sky_humidity_0h
     - sensor.dark_sky_humidity_3h
     - sensor.dark_sky_icon
     - sensor.dark_sky_icon_0d
     - sensor.dark_sky_icon_0h
     - sensor.dark_sky_icon_3h
     - sensor.dark_sky_precip_probability	
     - sensor.dark_sky_precip_probability_0d	
     - sensor.dark_sky_precip_probability_0h	
     - sensor.dark_sky_precip_probability_3h	
     - sensor.dark_sky_summary	
     - sensor.dark_sky_summary_0d	
     - sensor.dark_sky_summary_0h	
     - sensor.dark_sky_summary_3h	
     - sensor.dark_sky_temperature	
     - sensor.dark_sky_temperature_0h	
     - sensor.dark_sky_temperature_3h	
     - sensor.dark_sky_wind_speed	
     - sensor.dark_sky_wind_speed_0d	
     - sensor.dark_sky_wind_speed_0h	
     - sensor.dark_sky_wind_speed_3h
     - sensor.date
     - sensor.date_time
     - sensor.date_time_iso
     - sensor.date_time_utc	
     - sensor.daylight