# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

my:

logger:
  default: error

group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
sensor: !include sensors.yaml
zone: !include zone.yaml
var: !include variables.yaml

discovery:
  ignore:
    - homekit

camera:
  - platform: xiaomi
    name: Camera
    host: '192.168.1.69'
    model: 'yi'
    password: !secret camera_pwd
    path: /tmp/sd/record

sonoff:
  username: !secret sonoff_mail
  password: !secret sonoff_pwd
  reload: always

yeelight:

deconz:
  host: '192.168.1.84'
  port: 8443

shell_command:
  reboot_camera_living_room: "curl http://192.168.1.69/cgi-bin/reboot.sh"

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  trusted_proxies: 
    - 192.168.1.84
    - 172.18.0.0/16


# Example configuration.yaml entry for the Telegram Bot
telegram_bot:
  - platform: polling
    api_key: !secret api_telegram
    allowed_chat_ids:
      - 925364597


# Example configuration.yaml entry for the notifier
notify:
  - name: telegram
    platform: telegram
    chat_id: 925364597


#FOR guest
input_select:
  guests:
    options:
      - home
      - not_home
    initial: not_home
    icon: mdi:guy-fawkes-mask


#influxdb:
#  host: localhost
#  port: 8086
#  database: hassio
#  username: hassio
#  password: hassio
#  max_retries: 3
#  default_measurement: state


# Text to speech
tts:
  - platform: google_translate

system_health:

webhook:

#termostato
climate:
  - platform: generic_thermostat
    name: Riscaldamento
    heater: switch.thermostat
    target_sensor: var.avg_house_temperature
    min_temp: 10
    max_temp: 25
    ac_mode: false
    target_temp: 19.5
    cold_tolerance: 0.2
    hot_tolerance : 0.1
    min_cycle_duration:
      seconds: 1800
    initial_hvac_mode: "off"
    away_temp: 15



binary_sensor:
  - platform: trend
    sensors:
      bath_humidity:
        entity_id: sensor.t_bathroom_2
        sample_duration: 7200
        min_gradient: 0.02
        device_class: moisture
  - platform: template
    sensors:
      television:
        icon_template: hass:television
        value_template: >-
          {{ state_attr('switch.sonoff_10009ce473', 'power')|int > 20 }}

#- platform: uptimerobot
#    api_key: !secret uptimerobot



homeassistant:
  packages: !include_dir_named packages
  customize:
    switch.sonoff_1000a539ca:
      device_class: lock
    switch.sonoff_1000a54613:
      device_class: light
    sensor.shelly_shdm_1_d1818c_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shem_c45bbe796e82_1_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shem_c45bbe796e82_2_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shrgbw2_011738_1_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shrgbw2_011738_2_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shrgbw2_011738_3_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shrgbw2_011738_4_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shrgbw2_011825_1_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shrgbw2_011825_2_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shrgbw2_011825_3_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shrgbw2_011825_4_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shrgbw2_f4337c_1_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shrgbw2_f4337c_2_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shrgbw2_f4337c_3_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shrgbw2_f4337c_4_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shrgbw2_f43a0c_1_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shrgbw2_f43a0c_2_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shrgbw2_f43a0c_3_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shrgbw2_f43a0c_4_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shsw_pm_84cca8aca64a_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shsw_pm_b901af_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shsw_pm_b906cb_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shsw_pm_b911e9_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shsw_pm_b984a1_total_consumption:
      device_class: energy
      state_class: total_increasing
    sensor.shelly_shsw_pm_c4b0f4_total_consumption:
      device_class: energy
      state_class: total_increasing

  allowlist_external_dirs:
    - /config/camera


api:

#hacs:
#  token: !secret token_hacs
#  theme: true

frontend:
  themes: !include_dir_merge_named themes

proximity:
  casa:
    zone: home
    devices:
      - device_tracker.iphone_di_roberto
      - device_tracker.tamar_s_iphone_2
    tolerance: 200
    unit_of_measurement: km 


recorder:
  purge_keep_days: 3
  include:
    domains:
      - script
      - light
      - switch
      - var
      - binary_sensor
    entity_globs:
      - sensor.t_*
    entities:
      - switch.thermostat
      - sensor.power_filtered
      - sensor.serbatoio_toy
      - sensor.odo_toy
      - proximity.casa
      - sensor.shelly_shdm_1_d1818c_total_consumption
      - sensor.shelly_shem_c45bbe796e82_1_total_consumption
      - sensor.shelly_shem_c45bbe796e82_2_total_consumption
      - sensor.shelly_shrgbw2_011738_1_total_consumption
      - sensor.shelly_shrgbw2_011738_2_total_consumption
      - sensor.shelly_shrgbw2_011738_3_total_consumption
      - sensor.shelly_shrgbw2_011738_4_total_consumption
      - sensor.shelly_shrgbw2_011825_1_total_consumption
      - sensor.shelly_shrgbw2_011825_2_total_consumption
      - sensor.shelly_shrgbw2_011825_3_total_consumption
      - sensor.shelly_shrgbw2_011825_4_total_consumption
      - sensor.shelly_shrgbw2_f4337c_1_total_consumption
      - sensor.shelly_shrgbw2_f4337c_2_total_consumption
      - sensor.shelly_shrgbw2_f4337c_3_total_consumption
      - sensor.shelly_shrgbw2_f4337c_4_total_consumption
      - sensor.shelly_shrgbw2_f43a0c_1_total_consumption
      - sensor.shelly_shrgbw2_f43a0c_2_total_consumption
      - sensor.shelly_shrgbw2_f43a0c_3_total_consumption
      - sensor.shelly_shrgbw2_f43a0c_4_total_consumption
      - sensor.shelly_shsw_pm_84cca8aca64a_total_consumption
      - sensor.shelly_shsw_pm_b901af_total_consumption
      - sensor.shelly_shsw_pm_b906cb_total_consumption
      - sensor.shelly_shsw_pm_b911e9_total_consumption
      - sensor.shelly_shsw_pm_b984a1_total_consumption
      - sensor.shelly_shsw_pm_c4b0f4_total_consumption
      - sensor.shelly_shem_c45bbe796e82_1_total_consumption_cost



history:
  include:
    domains:
      - script
      - light
      - switch
      - var
      - binary_sensor
    entity_globs:
      - sensor.t_*
    entities:
      - switch.thermostat
      - sensor.power_filtered
      - sensor.serbatoio_toy
      - sensor.odo_toy
      - proximity.casa
      - sensor.shelly_shdm_1_d1818c_total_consumption
      - sensor.shelly_shem_c45bbe796e82_1_total_consumption
      - sensor.shelly_shem_c45bbe796e82_2_total_consumption
      - sensor.shelly_shrgbw2_011738_1_total_consumption
      - sensor.shelly_shrgbw2_011738_2_total_consumption
      - sensor.shelly_shrgbw2_011738_3_total_consumption
      - sensor.shelly_shrgbw2_011738_4_total_consumption
      - sensor.shelly_shrgbw2_011825_1_total_consumption
      - sensor.shelly_shrgbw2_011825_2_total_consumption
      - sensor.shelly_shrgbw2_011825_3_total_consumption
      - sensor.shelly_shrgbw2_011825_4_total_consumption
      - sensor.shelly_shrgbw2_f4337c_1_total_consumption
      - sensor.shelly_shrgbw2_f4337c_2_total_consumption
      - sensor.shelly_shrgbw2_f4337c_3_total_consumption
      - sensor.shelly_shrgbw2_f4337c_4_total_consumption
      - sensor.shelly_shrgbw2_f43a0c_1_total_consumption
      - sensor.shelly_shrgbw2_f43a0c_2_total_consumption
      - sensor.shelly_shrgbw2_f43a0c_3_total_consumption
      - sensor.shelly_shrgbw2_f43a0c_4_total_consumption
      - sensor.shelly_shsw_pm_84cca8aca64a_total_consumption
      - sensor.shelly_shsw_pm_b901af_total_consumption
      - sensor.shelly_shsw_pm_b906cb_total_consumption
      - sensor.shelly_shsw_pm_b911e9_total_consumption
      - sensor.shelly_shsw_pm_b984a1_total_consumption
      - sensor.shelly_shsw_pm_c4b0f4_total_consumption
      - sensor.shelly_shem_c45bbe796e82_1_total_consumption_cost


logbook:
  include:
    domains:
      - script
      - light
      - switch
      - var
      - binary_sensor
    entity_globs:
      - sensor.t_*
    entities:
      - switch.thermostat
      - sensor.power_filtered
      - sensor.serbatoio_toy
      - sensor.odo_toy
      - proximity.casa
      - sensor.shelly_shdm_1_d1818c_total_consumption
      - sensor.shelly_shem_c45bbe796e82_1_total_consumption
      - sensor.shelly_shem_c45bbe796e82_2_total_consumption
      - sensor.shelly_shrgbw2_011738_1_total_consumption
      - sensor.shelly_shrgbw2_011738_2_total_consumption
      - sensor.shelly_shrgbw2_011738_3_total_consumption
      - sensor.shelly_shrgbw2_011738_4_total_consumption
      - sensor.shelly_shrgbw2_011825_1_total_consumption
      - sensor.shelly_shrgbw2_011825_2_total_consumption
      - sensor.shelly_shrgbw2_011825_3_total_consumption
      - sensor.shelly_shrgbw2_011825_4_total_consumption
      - sensor.shelly_shrgbw2_f4337c_1_total_consumption
      - sensor.shelly_shrgbw2_f4337c_2_total_consumption
      - sensor.shelly_shrgbw2_f4337c_3_total_consumption
      - sensor.shelly_shrgbw2_f4337c_4_total_consumption
      - sensor.shelly_shrgbw2_f43a0c_1_total_consumption
      - sensor.shelly_shrgbw2_f43a0c_2_total_consumption
      - sensor.shelly_shrgbw2_f43a0c_3_total_consumption
      - sensor.shelly_shrgbw2_f43a0c_4_total_consumption
      - sensor.shelly_shsw_pm_84cca8aca64a_total_consumption
      - sensor.shelly_shsw_pm_b901af_total_consumption
      - sensor.shelly_shsw_pm_b906cb_total_consumption
      - sensor.shelly_shsw_pm_b911e9_total_consumption
      - sensor.shelly_shsw_pm_b984a1_total_consumption
      - sensor.shelly_shsw_pm_c4b0f4_total_consumption
      - sensor.shelly_shem_c45bbe796e82_1_total_consumption_cost
