# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

logger:
  default: error

group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
sensor: !include sensors.yaml
zone: !include zone.yaml
var: !include variables.yaml

#panel_iframe:
#  influxdb:
#    title: InfluxDB
#    icon: mdi:chart-areaspline
#    url: https://roroby.duckdns.org:8888
#  grafana:
#    title: Grafana
#    icon: mdi:chart-timeline
#    url: https://roroby.duckdns.org:3000

discovery:
  ignore:
    - homekit

ble_monitor:

camera:
  - platform: xiaomi
    name: Camera
    host: '192.168.1.69'
    model: 'yi'
    password: !secret camera_pwd
    path: /tmp/sd/record

#camera:
#  - platform: onvif
#    host: 192.168.1.94
#    port: 554
#    username: admin
#    profile: 2
#    password: !secret camera_yoosee

#sonoffLAN
sonoff:
  username: !secret sonoff_mail
  password: !secret sonoff_pwd
  reload: always

yeelight:


shell_command:
  reboot_camera_living_room: "curl http://192.168.1.69/cgi-bin/reboot.sh"

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
#  base_url: !secret url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem


# Example configuration.yaml entry for the Telegram Bot
telegram_bot:
  - platform: polling
    api_key: !secret api_telegram
    allowed_chat_ids:
      - 925364597


# Example configuration.yaml entry for the notifier
notify:
  - name: telegram
    platform: telegram
    chat_id: 925364597


#FOR guest
input_select:
  guests:
    options:
      - home
      - not_home
    initial: not_home
    icon: mdi:guy-fawkes-mask


influxdb:
  host: localhost
  port: 8086
  database: hassio
  username: hassio
  password: hassio
  max_retries: 3
  default_measurement: state

#Bluethoot
#device_tracker:
#  - platform: bluetooth_tracker

# Text to speech
tts:
  - platform: google_translate

system_health:

webhook:

#termostato
climate:
  - platform: generic_thermostat
    name: Riscaldamento
    heater: switch.thermostat
    target_sensor: var.avg_house_temperature
    min_temp: 10
    max_temp: 25
    ac_mode: false
    target_temp: 19.5
    cold_tolerance: 0.2
    hot_tolerance : 0.1
    min_cycle_duration:
      seconds: 1800
    initial_hvac_mode: "off"
    away_temp: 15



binary_sensor:
  - platform: trend
    sensors:
      bath_humidity:
        entity_id: sensor.t_bathroom_2
        sample_duration: 7200
        min_gradient: 0.02
        device_class: moisture
  - platform: template
    sensors:
      television:
        icon_template: hass:television
        value_template: >-
          {{ state_attr('switch.sonoff_10009ce473', 'power')|int > 20 }}



homeassistant:
  packages: !include_dir_named packages
  customize:
    switch.sonoff_1000a539ca:
      device_class: lock
    switch.sonoff_1000a54613:
      device_class: light
  allowlist_external_dirs:
    - /config/camera


api:

#hacs:
#  token: !secret token_hacs
#  theme: true

frontend:
  themes: !include_dir_merge_named themes


recorder:
  exclude:
    domains:
      - automations
    entity_globs:
      - sensor.dark_sky*
      - sensor.tim*
      - sensor.date*
      - sensor.tr*
      - sensor.when*
      - sensor.where*
      - sensor.ritardo*
      - sensor.riscaldamento*
      - sensor.pow1*
      - sensor.temperatura*_shelly


history:
  exclude:
    domains:
      - automations
    entity_globs:
      - sensor.dark_sky*
      - sensor.tim*
      - sensor.date*
      - sensor.tr*
      - sensor.when*
      - sensor.where*
      - sensor.ritardo*
      - sensor.riscaldamento*
      - sensor.pow1*
      - sensor.temperatura*_shelly