# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
sensor: !include sensors.yaml
zone: !include zone.yaml
var: !include variables.yaml

discovery:
  ignore:
    - homekit
  
#sonoffLAN
sonoff:
  username: !secret sonoff_mail
  password: !secret sonoff_pwd
 # reload: always

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

#FOR guest
input_select:
  guests:
    options:
      - home
      - not_home
    initial: not_home
    icon: mdi:guy-fawkes-mask

influxdb:
  host: influxdb
  port: 8086
  database: homeassistant
  username: hassio
  password: hassio
  max_retries: 3
  default_measurement: state

#Bluethoot
device_tracker:
  - platform: bluetooth_tracker

# Text to speech
tts:
  - platform: google_translate
  
system_health:

#shelly_integration
shelly:

webhook:

#termostato
climate:
  - platform: generic_thermostat
    name: Riscaldamento
    heater: switch.sonoff_2
    target_sensor: sensor.house_temperature
    min_temp: 10
    max_temp: 25
    ac_mode: false
    target_temp: 19.5
    min_cycle_duration:
      seconds: 120
    initial_hvac_mode: "off"
    away_temp: 15



binary_sensor:
  - platform: trend
    sensors:
      bath_humidity:
        entity_id: sensor.multi_sensor_3_3
        sample_duration: 7200
        min_gradient: 0.02
        device_class: moisture
  - platform: rpi_gpio
    ports:
      #2: test2 no serigrafia
      #3: test3 no serigrafia
      4: test4
      5: test5     #non collegato
      6: test6     #non collegato
      #7: test7 no serigrafia
      #8: test8 no serigrafia
      #9: test9 no serigrafia
      #10: test10 no serigrafia
      #11: test11 no serigrafia
      12: test12
      13: test13   #non collegato
      #14: test14   no serigrafia
      #15: test15 no serigrafia
      16: test16
      17: test17
      18: test18
      19: test19   #non collegato
      20: test20
      21: test21
      22: test22
      23: test23
      24: test24
      25: test25
      27: test27

yeelight:
  devices:
    192.168.1.64:
      name: entrance
    192.168.1.68:
      name: bagno
    192.168.1.66:
      name: Livingroom
  
api:

hacs:
  token: !secret token_hacs
  theme: true

frontend:
  themes: !include_dir_merge_named themes

input_datetime:
  livingroom_open:
    has_date: true
    has_time: true
  livingroom_close:
    has_date: true
    has_time: true
  livingroom_lasttime:
    has_time: true
    has_date: false

recorder:
  exclude:
    entities:
     - sensor.tr800
     - sensor.ritardo_800
     - sensor.where_800
     - sensor.when_800
     - sensor.tr735
     - sensor.ritardo_735
     - sensor.where_735
     - sensor.when_735
     - sensor.tr730
     - sensor.ritardo_730
     - sensor.where_730
     - sensor.when_730
     - sensor.tr700
     - sensor.ritardo_700
     - sensor.where_700
     - sensor.when_700
     - sensor.tr630
     - sensor.ritardo_630
     - sensor.where_630
     - sensor.when_630

history:
  exclude:
    entities:
     - sensor.tr800
     - sensor.ritardo_800
     - sensor.where_800
     - sensor.when_800
     - sensor.tr735
     - sensor.ritardo_735
     - sensor.where_735
     - sensor.when_735
     - sensor.tr730
     - sensor.ritardo_730
     - sensor.where_730
     - sensor.when_730
     - sensor.tr700
     - sensor.ritardo_700
     - sensor.where_700
     - sensor.when_700
     - sensor.tr630
     - sensor.ritardo_630
     - sensor.where_630
     - sensor.when_630