- alias: 'action test'
  trigger:
    platform: state
    entity_id:
      - binary_sensor.m_dressing
      - binary_sensor.m_bathroom
      - binary_sensor.ma_one
      - binary_sensor.ma_2
      - binary_sensor.ma_3
      - binary_sensor.w_livingroom # bedroom door
      - binary_sensor.w_bathroom
      - sensor.yicam
    to: 'on'
  action:
    service: notify.telegram
    data:
      title: '*Send a message*'
      message: "That's an example that _sends_ a *formatted* message with a custom inline keyboard."
      data:
        inline_keyboard:
          - 'Task 1:/command1, Task 2:/command2'
          - 'Task 3:/command3, Task 4:/command4'

    