- alias: 'Alarm'
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.m_dressing
    - binary_sensor.m_bathroom
    - binary_sensor.ma_one
    - binary_sensor.ma_2
    - binary_sensor.ma_3
    - binary_sensor.w_livingroom # bedroom door
    - binary_sensor.w_bathroom
    - sensor.yicam
    to: 'on'
    
  condition:
    condition: state
    entity_id: group.family
    state: 'not_home'
  action:
  - data_template:
      message: 'Detected movment of {{ trigger.from_state.attributes.friendly_name }}'
      title: 'ALARM'
      data:
        inline_keyboard:
          - 'Task 1:/command1, Task 2:/command2'
          - 'Task 3:/command3, Task 4:/command4'
    service: notify.telegram
    