- alias: 'Alarm'
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.m_dressing
    - binary_sensor.m_bathroom
    - binary_sensor.ma_one
    - binary_sensor.ma_2
    - binary_sensor.ma_3
    - binary_sensor.w_livingroom
    - sensor.yicam
    to: 'on'
  condition:
    condition: state
    entity_id: group.family
    state: 'not_home'
  action:
  - data_template:
      message: 'Detected movment of {{ trigger.from_state.attributes.friendly_name }}'
      title: 'ALARM'
    service: notify.mobile_app_iphone_di_roberto
    