- alias: 'Alarm'
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.water_sensor
    - binary_sensor.water_sensor_2
    - binary_sensor.water_sensor_3
    to: 'on'
  action:
    - service: telegram_bot.send_message
      data_template:
        title: "Wet Detected"
        message: '{{ now().strftime("%H:%M:%S") }} - wet {{trigger.entity_id}} '
    - service: light.turn_on
        entity_id: light.livingroom
        brightness: 255
        color_name: blu
        flash: short

    