- id: 'Away Mode'
  alias: Switch all off if we are away
  trigger:
    platform: state
    entity_id: group.family
    from: home
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: switch.turn_off
      entity_id: 
        - switch.sonoff
        - switch.tasmota
        - switch.sonoff_100056b199_1
        - switch.sonoff_100056b199_2
        - switch.sonoff_1000a5758e  
    - service: climate.set_temperature
      data:
        entity_id: climate.riscaldamento
        temperature: 15

- alias: Try update phone position
  trigger:
    platform: state
    entity_id: group.inside_presences
    to: 'off'
    for:
      minutes: 40
  condition:
    - condition: template
      value_template: "{{ ((as_timestamp(now()) - as_timestamp(as_timestamp(states.sensor.tamar_s_iphone_geocoded_location_2.last_updated) |timestamp_local)) /3600) |round > 12 }}"
    - condition: time
      after: '08:00:00'
      before: '22:00:00'
    - condition: state
      entity_id: group.family
      state: home 
  action:
    - service: notify.mobile_app_tamar_s_iphone
      data:
        message: "request_location_update"
    - service: telegram_bot.send_message
      data_template:
        title: try to update phone information 
        message: 'last update phone at: {{ as_timestamp(states.sensor.tamar_s_iphone_geocoded_location_2.last_updated) |timestamp_local }} try to update @ {{ now().strftime("%H:%M:%S") }}'

- id: 'Away Mode no phone info'
  alias: Away Mode no phone info
  trigger:
    platform: state
    entity_id: group.inside_presences
    to: 'off'
    for:
      minutes: 45
  condition:
    - condition: template
      value_template: "{{ ((as_timestamp(now()) - as_timestamp(as_timestamp(states.sensor.tamar_s_iphone_geocoded_location_2.last_updated) |timestamp_local)) /3600) |round > 12 }}"
    - condition: time
      after: '08:00:00'
      before: '22:00:00'
    - condition: state
      entity_id: group.family
      state: home 
    - condition: template
      value_template: "{{ not is_state('person.roby', 'home') }}"
  action:
    - service: telegram_bot.send_message
      data_template:
        title: Away Mode while no phone info
        message: 'No motion detected in house, last update phone at: {{ as_timestamp(states.sensor.tamar_s_iphone_geocoded_location_2.last_updated) |timestamp_local }}
         Away mode set in 5 min from now : {{ now().strftime("%H:%M:%S") }}'
    - delay: '00:05:00'
    - service: light.turn_off
      entity_id: group.all_lights
    - service: switch.turn_off
      entity_id: 
        - switch.sonoff
        - switch.tasmota
        - switch.sonoff_100056b199_1
        - switch.sonoff_100056b199_2
        - switch.sonoff_1000a5758e 
    - service: climate.set_temperature
      data:
        entity_id: climate.riscaldamento
        temperature: 15
    - service: telegram_bot.send_message
      data_template:
        title: Away Mode setted
        message: 'No motion detected in house, last update phone at: {{ as_timestamp(states.sensor.tamar_s_iphone_geocoded_location_2.last_updated) |timestamp_local }}
         Away mode setted now : {{ now().strftime("%H:%M:%S") }}'