- alias: humidity notification ok - close windows
  trigger:
    - platform: state
      entity_id: binary_sensor.w_bathroom
      to: on
      for:
        minutes: 5
 condition:
    - condition: template
      value_template: "{{ states("sensor.multi_sensor_4") |int - states("sensor.multi_sensor_3_3") |int> 0  or
                          states("sensor.house_temperature") |round(1)*10 |int - states("sensor.multi_sensor_3_2") |round(1)*10 |int ) -20 >0 }}"
  action:
    service: notify.mobile_app_iphone_di_roberto
    data_template:
      title: "close bathroom window"
      message: >
        {{ now().strftime("%H:%M:%S")  - can close bathroom windows humidity now at states("sensor.multi_sensor_3_3") % ;  temperature  states("sensor.multi_sensor_3_2") °C }} 

- alias: humidity notification wornk - apen windows
  trigger:
    - platform: state
      entity_id: binary_sensor.w_bathroom
      to: off
      for:
        minutes: 5
 condition:
    - condition: template
      value_template: "{{ states("sensor.multi_sensor_4") |int - states("sensor.multi_sensor_3_3") |int < 0  and states("sensor.multi_sensor_3_3") |int >70 }}
  action:
    service: notify.mobile_app_iphone_di_roberto
    data_template:
      title: "Open bathroom window"
      message: >
        {{ now().strftime("%H:%M:%S")  - should open bathroom windows humidity now at states("sensor.multi_sensor_3_3") % ;  temperature  states("sensor.multi_sensor_3_2") °C }} 
