# - alias: 'Light1 - raise-up bathroom motion '
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.m_bathroom
#       to: 'on'
#   action:
#     service: light.turn_on
#     entity_id: light.bathroom
#     data_template:
#       brightness: >
#            {% if  now().hour < 6 %} 
#               70
#            {% elif now().hour >= 6 and now().hour < 7 %} 
#               128
#            {% elif now().hour >= 7 and now().hour < 20  %}
#               255
#            {% elif now().hour >= 20 and now().hour < 22  %}
#               128
#            {% elif now().hour >= 22  %}
#               70
#            {% endif %}
#       kelvin: '{% if now().hour >= 19 %}1700{% elif now().hour <= 7 %}1700{% else %}2500{% endif %}'
#       transition: 4
   
- alias: 'Light2 - raise-down bathroom light at'
  trigger:
    platform: state
    entity_id: binary_sensor.m_bathroom
    to: 'off'
    for:
      minutes: 10
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    # - service: light.turn_on
    #   entity_id: light.bathroom
    #   data_template:
    #     transition: 10
    #     brightness: 1
    - service: light.turn_off
      data_template:
        entity_id: light.l_bathroom_main
    - service: switch.turn_off
      entity_id: 
        - switch.sonoff_1000a5758e  

#Light Temperature by sunlight

- alias: ' Light3 - automation color/brightness on dim lights '
  trigger:
    - platform: state
      entity_id: group.family
      to: home
    - platform: time_pattern
      minutes: /10
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    - service: light.turn_on
      data_template:
        entity_id: >
               {% for item in states | selectattr('entity_id', 'in', state_attr('group.dim_lights', 'entity_id')) | selectattr('state', 'equalto', 'on') -%}
               {% if not loop.first %},{% endif %}{{ item.entity_id }}
               {%- endfor %}
        brightness: >
           {% if  now().hour < 7 %} 
              1
           {% elif now().hour >= 7 and now().hour < 8 %} 
              75
           {% elif now().hour >= 8 and now().hour < 17  %}
              255
           {% elif now().hour >= 17 and now().hour < 20  %}
              100
           {% elif now().hour >= 20 and now().hour < 21  %}
              30
           {% elif now().hour >= 23  %}
              1
           {% endif %}
        kelvin: '{% if now().hour >= 17 %}1700{% elif now().hour <= 8 %}1700{% else %}2500{% endif %}'
        transition: 120

- alias: 'Light4 - automation brightness triggered by swicth on'
  trigger:
    - platform: state
      entity_id: 
        - light.l_cucina_2
        - light.l_dressingroom
        - light.l_bedroom #bedroom zigbee bulb
        - light.shelly_shdm_1_d1818c
      to: 'on'
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    - service: light.turn_on
      data_template:
        entity_id: "{{ trigger.entity_id }}"
        brightness: >
           {% if  now().hour < 7 %} 
              1
           {% elif now().hour >= 7 and now().hour < 8 %} 
              75
           {% elif now().hour >= 8 and now().hour < 17  %}
              255
           {% elif now().hour >= 17 and now().hour < 20  %}
              100
           {% elif now().hour >= 20 and now().hour < 21  %}
              30
           {% elif now().hour >= 23  %}
              1
           {% endif %}
        transition: 3

- alias: ' Light5 - automation light back home '
  trigger:
    - platform: state
      entity_id: group.family
      to: home
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    - service: light.turn_on
      entity_id: group.back_home_lights

- alias: 'Light15 - bathroom celing light '
  trigger:
    - platform: state
      entity_id: 
        - switch.sonoff_1000a53f4b
      to:
        - 'on'
        - 'off'
  condition:
    condition: state
    entity_id: light.l_bathroom_main
    state: 'off'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.l_bathroom_main
        brightness: >
           {% if  now().hour < 6 %} 
              1
           {% elif now().hour >= 6 and now().hour < 7 %} 
              128
           {% elif now().hour >= 7 and now().hour < 20  %}
              255
           {% elif now().hour >= 20 and now().hour < 21  %}
              128
           {% elif now().hour >= 21 and now().hour < 23  %}
              30
           {% elif now().hour >= 23  %}
              1
           {% endif %}
        transition: 4

- alias: 'Light16 - bathroom celing light '
  trigger:
    - platform: state
      entity_id: 
        - switch.sonoff_1000a53f4b
  condition:
    condition: state
    entity_id: light.l_bathroom_main
    state: 'on'
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.l_bathroom_main

- alias: 'Light17 - balcony south '
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.m_balcony_south
      to: 'on'
  condition:
    condition: state  # from sunset until sunrise
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    - service: switch.turn_on
      data_template:
        entity_id: switch.sonoff_1000a495ae

- alias: 'Light18 - balcony south '
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.m_balcony_south
      to: 'off'
      for:
       minutes: 1
  action:
    - service: switch.turn_off
      data_template:
        entity_id: switch.sonoff_1000a495ae
        

        
       
         
   #fan on wall connection
- alias: 'Light22 - fan on wall '
  trigger:
    - platform: state 
      entity_id:
        - switch.sonoff_10008cbb5e_1
      to: 'on'
  action:
    - service: fan.turn_on
      entity_id: 
        - fan.sonoff_1000994c1d

        
- alias: 'Light23 - fan on wall '
  trigger:
    - platform: state 
      entity_id:
        - switch.sonoff_10008cbb5e_1
      to: 'off'
  action:
    - service: fan.turn_off
      entity_id: 
        - fan.sonoff_1000994c1d
    
- alias: 'Light24 - fan on wall '
  trigger:
    - platform: state 
      entity_id:
        - fan.sonoff_1000994c1d
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.sonoff_10008cbb5e_1
        
- alias: 'Light25 - fan on wall '
  trigger:
    - platform: state 
      entity_id:
        - fan.sonoff_1000994c1d
      to: 'off'
  action:
    - service: switch.turn_off
      entity_id: 
        - switch.sonoff_10008cbb5e_1

- alias: Button Emma single press 
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: switch_emma
      event: 1002
  action:
    - service: light.toggle
      entity_id: light.shelly_shrgbw2_011825_4 #emma owl

# - alias: Button Emma long press start 
#   trigger:
#     platform: event
#     event_type: deconz_event
#     event_data:
#       id: switch_emma
#       event: 1001
#   action:
#     - service: yeelight.start_flow
#       entity_id: light.yeelight_emma # emma bedroom yeeelight
#       transitions:
#         - RGBTransition:
#            - 0
#            - 255
#            - 255
#            - 5000
#            - 100
#         - RGBTransition:
#            - 255
#            - 0
#            - 255
#            - 5000
#            - 100
#         - RGBTransition:
#            - 255
#            - 255
#            - 0
#            - 5000
#            - 100

# - alias: Button Emma long press release 
#   trigger:
#     platform: event
#     event_type: deconz_event
#     event_data:
#       id: switch_emma
#       event: 1003
#   action:
#     - service: yeelight.set_mode
#       entity_id: light.yeelight_emma # emma bedroom yeeelight
#       mode: rgb

- alias: Button Emma double press 
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: switch_emma
      event: 1004
  action:
    - service: light.toggle
      entity_id: light.shelly_shdm_1_d1818c # emma bedroom main





- alias: 'Light28 - nightlight off'
  trigger:
    - platform: state
      entity_id: light.shelly_shrgbw2_f43a0c_1 #bedroom Led warm
      to: 'on'
  action:
    - service: light.turn_off
      entity_id: 
        - light.shelly_shrgbw2_f43a0c_2