- id: 'Light1'
  alias: raise-up bathroom light at 100% with motion 
  trigger:
    platform: state
    entity_id: binary_sensor.m_bathroom
    to: 'on'
  condition:
    condition: time
    after: 07:00:00
    before: '19:00:00'
  action:
    service: light.turn_on
    entity_id: light.bagno
    data_template:
      transition: 4
      brightness: 255
      
- id: 'Light2'
  alias: raise-up bathroom light at 50% with motion 
  trigger:
    platform: state
    entity_id: binary_sensor.m_bathroom
    to: 'on'
  condition:
    condition: time
    after: '19:00:00'
  action:
    service: light.turn_on
    entity_id: light.bagno
    data_template:
      transition: 4
      brightness: 70
      
- id: 'Light3'
  alias: raise-down bathroom light 
  trigger:
    platform: state
    entity_id: binary_sensor.m_bathroom
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: time
    after: 07:00:00
    before: '19:00:00'
  action:
    service: light.turn_on
    entity_id: light.bagno
    data_template:
      transition: 90
      brightness: 10
      
- id: 'Light4'
  alias: raise-down bathroom light at (night)
  trigger:
    platform: state
    entity_id: binary_sensor.m_bathroom
    to: 'off'
    for:
      minutes: 10
  condition:
    condition: time
    after: '19:00:00'
  action:
    service: light.turn_on
    entity_id: light.bagno
    data_template:
      transition: 45
      brightness: 1

#Light Temperature by sunlight

- alias: ' Light5'
  trigger:
    - platform: state
      entity_id: group.family
      to: home
    - platform: sun
      event: sunset
      offset: "00:01:00"
    - platform: sun
      event: sunrise
      offset: "00:01:00"
    - platform: state
      entity_id: group.rgb_lights
      to: 'on'
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    - service: light.turn_on
      entity_id: group.rgb_lights
      data_template:
        brightness: '{% if as_timestamp(now())|int > as_timestamp(states.sun.sun.attributes.next_setting)|int %}30{% elif as_timestamp(now())|int < as_timestamp(states.sun.sun.attributes.next_rising)|int %}30{% else %}100{% endif %}'
        transition: 300
    - service: yeelight.set_color_temp_scene
      entity_id: group.rgb_lights
      data_template:
        kelvin: '{% if as_timestamp(now())|int > as_timestamp(states.sun.sun.attributes.next_setting)|int %}1700{% elif as_timestamp(now())|int < as_timestamp(states.sun.sun.attributes.next_rising)|int %}1700{% else %}3000{% endif %}'
   
    
- alias: ' Light6'
  trigger:
    - platform: state
      entity_id: group.family
      to: home
    - platform: sun
      event: sunset
      offset: "00:01:00"
    - platform: sun
      event: sunrise
      offset: "00:01:00"
    - platform: state
      entity_id: light.l_cucina_2
      to: 'on'
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    - service: light.turn_on
      entity_id: light.l_cucina_2
      data_template:
        brightness: '{% if as_timestamp(now())|int > as_timestamp(states.sun.sun.attributes.next_setting)|int %}30{% elif as_timestamp(now())|int < as_timestamp(states.sun.sun.attributes.next_rising)|int %}30{% else %}100{% endif %}'
        transition: 300 