

- alias: 'Entrancelight - main '
  trigger:
    - platform: state 
      entity_id: switch.sonoff_1000a4166e
      to: 
        - 'off'
        - 'on'
  action:
    - service: light.toggle
      entity_id: 
        - light.shelly_shrgbw2_f4337c_4



#        switch.sonoff_10009ce05a

