
#wall led connection
- alias: 'LivingLight - table LED to on'
  trigger:
    - platform: state 
      entity_id:
        - switch.sonoff_10008cbb1d_2 #sonoff_to_mqtt_led
      to:
        - 'on'
        - 'off'
  condition:
    - condition: state
      entity_id: switch.sonoff # sonoff mqtt table light
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.sonoff # sonoff mqtt table light
        
- alias: 'LivingLight - table LED to off'
  trigger:
    - platform: state 
      entity_id:
        - switch.sonoff_10008cbb1d_2 #sonoff_to_mqtt_led
      to:
        - 'on'
        - 'off'
  condition:
    - condition: state
      entity_id: switch.sonoff # sonoff mqtt table light
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: 
        - switch.sonoff # sonoff mqtt table light

- alias: 'LivingLight - Livingroom Daily button on'
  trigger:
    - platform: state
      entity_id: 
        - switch.sonoff_10008cbb5e_2 # sonoff touch2 sceene day
      to: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.living_room_sceene
        option: 'Daylight'
    - service: switch.turn_off
      entity_id: 
        - switch.sonoff_10008cbb5e_3 # sonoff touch2 sceene night
        
- alias: 'LivingLight - Livingroom Daily button off'
  trigger:
    - platform: state
      entity_id: 
        - switch.sonoff_10008cbb5e_2 # sonoff touch2 sceene day
      to: 'off'
  condition:
      condition: state
      entity_id: switch.sonoff_10008cbb5e_3 # sonoff touch2 sceene night
      state: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.living_room_sceene
        option: 'Off'
         
         
- alias: 'LivingLight - Livingroom Night button on'
  trigger:
    - platform: state
      entity_id: 
        - switch.sonoff_10008cbb5e_3 # sonoff touch2 sceene night
      to: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.living_room_sceene
        option: 'Evening'
    - service: switch.turn_off
      entity_id: 
        - switch.sonoff_10008cbb5e_2 # sonoff touch2 sceene day
        
- alias: 'LivingLight - Livingroom Night button off'
  trigger:
    - platform: state
      entity_id: 
        - switch.sonoff_10008cbb5e_3 # sonoff touch2 sceene night
      to: 'off'
  condition:
      condition: state
      entity_id: switch.sonoff_10008cbb5e_2 # sonoff touch2 sceene day
      state: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.living_room_sceene
        option: 'Off'

         
 
- alias: 'LivingLight - Livingroom Daylight '
  trigger:
    - platform: state
      entity_id: 
        - input_select.living_room_sceene
      to: 'Daylight'
  action:
    - service: switch.turn_on
      entity_id: 
       - switch.sonoff_10008cbb1d_3 #sonoff_to_yeelight
    - service: switch.turn_off
      entity_id: 
       - switch.sonoff
    - service: light.turn_on
      data_template:
        entity_id: 
         - light.yeelight_l_corner
         - light.yeelight_l_table
        brightness: 255
        kelvin: 2500
        transition: 10
    - service: light.turn_on
      data_template:
        entity_id: 
         - light.shelly_shrgbw2_f4337c_1 #livingroom warm led
         - light.shelly_shrgbw2_f4337c_2 #livingroom natural led
         - light.shelly_shrgbw2_011738_1 #livingroom closet warm led2
        brightness_pct: 100
        transition: 30
    - service: switch.turn_on
      entity_id: 
        - switch.sonoff_10008cbb5e_2 # sonoff touch2 sceene day
    - service: switch.turn_off
      entity_id: 
        - switch.sonoff_10008cbb5e_3 # sonoff touch2 sceene night

- alias: 'LivingLight - Livingroom Dinner '
  trigger:
    - platform: state
      entity_id: 
        - input_select.living_room_sceene
      to: 'Dinner'
  action:
    - service: switch.turn_on
      entity_id: 
       - switch.sonoff_10008cbb1d_3 #sonoff_to_yeelight
       - switch.sonoff
    - service: light.turn_on
      data_template:
        entity_id: 
         - light.yeelight_l_corner
         - light.yeelight_l_table
        brightness: 255
        kelvin: 2500
        transition: 10
    - service: light.turn_on
      data_template:
        entity_id: 
         - light.shelly_shrgbw2_f4337c_1 #livingroom warm led
         - light.shelly_shrgbw2_f4337c_2 #livingroom natural led
         - light.shelly_shrgbw2_011738_1 #livingroom closet warm led2
        brightness_pct: 100
        transition: 30
    - service: switch.turn_on
      entity_id: 
        - switch.sonoff_10008cbb5e_2 # sonoff touch2 sceene day
    - service: switch.turn_off
      entity_id: 
        - switch.sonoff_10008cbb5e_3 # sonoff touch2 sceene night
        
- alias: 'LivingLight - Livingroom Relax '
  trigger:
    - platform: state
      entity_id: 
        - input_select.living_room_sceene
      to: 'Relax'
  action:
    - service: switch.turn_off
      entity_id: 
       - switch.sonoff_10008cbb1d_3 #sonoff_to_yeelight
       - switch.sonoff
    - service: light.turn_on
      data_template:
        entity_id: 
         - light.yeelight_l_corner
         - light.yeelight_l_table
        brightness: 1
        kelvin: 1700
        transition: 10
    - service: light.turn_on
      data_template:
        entity_id: 
         - light.shelly_shrgbw2_f4337c_1 #livingroom warm led
         - light.shelly_shrgbw2_011738_1 #livingroom closet warm led2
        brightness_pct: 5
        transition: 30
    - service: light.turn_off
      data_template:
        entity_id: 
         - light.shelly_shrgbw2_f4337c_2 #livingroom natural led
    - service: switch.turn_on
      entity_id: 
        - switch.sonoff_10008cbb5e_3 # sonoff touch2 sceene night
    - service: switch.turn_off
      entity_id: 
        - switch.sonoff_10008cbb5e_2 # sonoff touch2 sceene day
         
- alias: 'LivingLight - Livingroom TV '
  trigger:
    - platform: state
      entity_id: 
        - input_select.living_room_sceene
      to: 'Tv'
  action:
    - service: switch.turn_off
      entity_id: 
       - switch.sonoff_10008cbb1d_3 #sonoff_to_yeelight
       - switch.sonoff # sonoff mqtt table light
    - service: light.turn_off
      data_template:
        entity_id: 
         - light.yeelight_l_corner
         - light.yeelight_l_table
        transition: 10
    - service: light.turn_on
      data_template:
        entity_id: 
         - light.shelly_shrgbw2_011738_1 #livingroom closet warm led2
         - light.shelly_shrgbw2_f4337c_3
        brightness_pct: 1
        transition: 30
    - service: light.turn_off
      data_template:
        entity_id: 
         - light.shelly_shrgbw2_f4337c_1 #livingroom warm led
         - light.shelly_shrgbw2_f4337c_2 #livingroom natural led
    - service: switch.turn_on
      entity_id: 
        - switch.sonoff_10008cbb5e_3 # sonoff touch2 sceene night
    - service: switch.turn_off
      entity_id: 
        - switch.sonoff_10008cbb5e_2 # sonoff touch2 sceene day
         
- alias: 'LivingLight - Livingroom Evening '
  trigger:
    - platform: state
      entity_id: 
        - input_select.living_room_sceene
      to: 'Evening'
  action:
    - service: switch.turn_off
      entity_id: 
       - switch.sonoff_10008cbb1d_3 #sonoff_to_yeelight
       - switch.sonoff # sonoff mqtt table light
    - service: light.turn_on
      data_template:
        entity_id: 
         - light.yeelight_l_corner
         - light.yeelight_l_table
        brightness: 20
        kelvin: 1700
        transition: 10
    - service: light.turn_on
      data_template:
        entity_id: 
         - light.shelly_shrgbw2_f4337c_1 #livingroom warm led
         - light.shelly_shrgbw2_011738_1 #livingroom closet warm led2
        brightness_pct: 50
        transition: 30
    - service: light.turn_on
      data_template:
        entity_id: 
         - light.shelly_shrgbw2_f4337c_2 #livingroom natural led
        brightness_pct: 10
        transition: 30
    - service: switch.turn_on
      entity_id: 
        - switch.sonoff_10008cbb5e_3 # sonoff touch2 sceene night
    - service: switch.turn_off
      entity_id: 
        - switch.sonoff_10008cbb5e_2 # sonoff touch2 sceene day


- alias: 'LivingLight - Livingroom Off '
  trigger:
    - platform: state
      entity_id: 
        - input_select.living_room_sceene
      to: 'Off'
  action:
    - service: switch.turn_off
      entity_id: 
       - switch.sonoff_10008cbb1d_3 #sonoff_to_yeelight
       - switch.sonoff # sonoff mqtt table light
    - service: light.turn_off
      data_template:
        entity_id: 
         - light.yeelight_l_corner
         - light.yeelight_l_table
         - light.shelly_shrgbw2_f4337c_1 #livingroom warm led
         - light.shelly_shrgbw2_011738_1 #livingroom closet warm led2
         - light.shelly_shrgbw2_f4337c_2 #livingroom natural led
    - service: switch.turn_off
      entity_id: 
        - switch.sonoff_10008cbb5e_2 # sonoff touch2 sceene day
        - switch.sonoff_10008cbb5e_3 # sonoff touch2 sceene night

    