#Light Temperature by sunlight

- id: ' Light3 - automation color/brightness on dim lights '
  alias: ' Light3 - automation color/brightness on dim lights '
  trigger:
    - platform: state
      entity_id: group.family
      to: home
    - platform: time_pattern
      minutes: /10
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: template
      value_template: "{{ states.light | selectattr('entity_id', 'in', state_attr('group.color_lights', 'entity_id')) | selectattr('state', 'equalto', 'on') |list |count > 0 }} "
  action:
    - service: light.turn_on
      data_template:
        entity_id: >
               {% for item in states | selectattr('entity_id', 'in', state_attr('group.color_lights', 'entity_id')) | selectattr('state', 'equalto', 'on') -%}
               {% if not loop.first %},{% endif %}{{ item.entity_id }}
               {%- endfor %}
        brightness: >
           {% if  now().hour < 7 %} 
              1
           {% elif now().hour >= 7 and now().hour < 8 %} 
              75
           {% elif now().hour >= 8 and now().hour < 17  %}
              255
           {% elif now().hour >= 17 and now().hour < 20  %}
              100
           {% elif now().hour >= 20 and now().hour < 21  %}
              30
           {% elif now().hour >= 23  %}
              1
           {% endif %}
        kelvin: '{% if now().hour >= 17 %}1700{% elif now().hour <= 8 %}1700{% else %}2500{% endif %}'
        transition: 120

- id: 'Light4 - automation brightness triggered by swicth on'
  alias: 'Light4 - automation brightness triggered by swicth on'
  trigger:
    - platform: state
      entity_id: 
        - light.l_kitchen
        - light.l_alma_bedroom
        - light.l_bedroom #bedroom zigbee bulb
        - light.shelly_shdm_1_d1818c
      to: 'on'
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    - service: light.turn_on
      data_template:
        entity_id: "{{ trigger.entity_id }}"
        brightness: >
           {% if  now().hour < 7 %} 
              1
           {% elif now().hour >= 7 and now().hour < 8 %} 
              75
           {% elif now().hour >= 8 and now().hour < 17  %}
              255
           {% elif now().hour >= 17 and now().hour < 20  %}
              100
           {% elif now().hour >= 20 and now().hour < 21  %}
              30
           {% elif now().hour >= 23  %}
              1
           {% endif %}
        transition: 3

- id: ' Light5 - automation light back home '
  alias: ' Light5 - automation light back home '
  trigger:
    - platform: state
      entity_id: group.family
      to: home
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    - service: light.turn_on
      entity_id: group.back_home_lights

- id: 'Light17 - balcony south '
  alias: 'Light17 - balcony south '
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.m_balcony_south
      to: 'on'
  condition:
    condition: state  # from sunset until sunrise
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    - service: switch.turn_on
      data_template:
        entity_id: switch.sonoff_1000a495ae

- id: 'Light18 - balcony south '
  alias: 'Light18 - balcony south '
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.m_balcony_south
      to: 'off'
      for:
       minutes: 1
  action:
    - service: switch.turn_off
      data_template:
        entity_id: switch.sonoff_1000a495ae
        

        
       
         
   #fan on wall connection
- id: 'Light22 - fan on wall '
  alias: 'Light22 - fan on wall '
  trigger:
    - platform: state 
      entity_id:
        - switch.sonoff_10008cbb5e_1
      to: 'on'
  action:
    - service: fan.turn_on
      entity_id: 
        - fan.sonoff_1000994c1d

        
- id: 'Light23 - fan on wall '
  alias: 'Light23 - fan on wall '
  trigger:
    - platform: state 
      entity_id:
        - switch.sonoff_10008cbb5e_1
      to: 'off'
  action:
    - service: fan.turn_off
      entity_id: 
        - fan.sonoff_1000994c1d
    
- id: 'Light24 - fan on wall '
  alias: 'Light24 - fan on wall '
  trigger:
    - platform: state 
      entity_id:
        - fan.sonoff_1000994c1d
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.sonoff_10008cbb5e_1
        
- id: 'Light25 - fan on wall '
  alias: 'Light25 - fan on wall '
  trigger:
    - platform: state 
      entity_id:
        - fan.sonoff_1000994c1d
      to: 'off'
  action:
    - service: switch.turn_off
      entity_id: 
        - switch.sonoff_10008cbb5e_1

- id: Button Emma single press 
  alias: Button Emma single press 
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: switch_emma
      event: 1002
  action:
    - service: light.toggle
      entity_id: light.shelly_shrgbw2_011825_4 #emma owl

# - alias: Button Emma long press start 
#   trigger:
#     platform: event
#     event_type: deconz_event
#     event_data:
#       id: switch_emma
#       event: 1001
#   action:
#     - service: yeelight.start_flow
#       entity_id: light.yeelight_emma # emma bedroom yeeelight
#       transitions:
#         - RGBTransition:
#            - 0
#            - 255
#            - 255
#            - 5000
#            - 100
#         - RGBTransition:
#            - 255
#            - 0
#            - 255
#            - 5000
#            - 100
#         - RGBTransition:
#            - 255
#            - 255
#            - 0
#            - 5000
#            - 100

# - alias: Button Emma long press release 
#   trigger:
#     platform: event
#     event_type: deconz_event
#     event_data:
#       id: switch_emma
#       event: 1003
#   action:
#     - service: yeelight.set_mode
#       entity_id: light.yeelight_emma # emma bedroom yeeelight
#       mode: rgb

- id: Button Emma double press 
  alias: Button Emma double press 
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: switch_emma
      event: 1004
  action:
    - service: light.toggle
      entity_id: light.shelly_shdm_1_d1818c # emma bedroom main


- id: Button Emma triple press 
  alias: Button Emma triple press 
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: switch_emma
      event: 1005
  action:
    - service: light.toggle
      entity_id: light.yeelight_emma
      
- id: Button Emma four press 
  alias: Button Emma four press 
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: switch_emma
      event: 1006
  action:
    - service: light.toggle
      entity_id: light.shelly_shrgbw2_011825_1

