- alias: 'Light1 - raise-up bathroom motion '
  trigger:
    - platform: state
      entity_id: binary_sensor.m_bathroom
      to: 'on'
  action:
    service: light.turn_on
    entity_id: light.bagno
    data_template:
      brightness: >
           {% if  now().hour < 6 %} 
              70
           {% elif now().hour >= 6 and now().hour < 7 %} 
              128
           {% elif now().hour >= 7 and now().hour < 20  %}
              255
           {% elif now().hour >= 20 and now().hour < 22  %}
              128
           {% elif now().hour >= 21  %}
              70
           {% endif %}
      kelvin: '{% if now().hour >= 19 %}1700{% elif now().hour <= 7 %}1700{% else %}2500{% endif %}'
      transition: 4
   
- alias: 'Light2 - raise-down bathroom light at'
  trigger:
    platform: state
    entity_id: binary_sensor.m_bathroom
    to: 'off'
    for:
      minutes: 10
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    - service: light.turn_on
      entity_id: light.bagno
      data_template:
        transition: 10
        brightness: 1
    - service: light.turn_off
      data_template:
        entity_id: light.l_bagno
    - service: switch.turn_off
      entity_id: 
        - switch.sonoff_1000a5758e  

#Light Temperature by sunlight

- alias: ' Light3 - automation color/brightness on dim lights '
  trigger:
    - platform: state
      entity_id: group.family
      to: home
    - platform: time_pattern
      minutes: /10
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    - service: light.turn_on
      data_template:
        entity_id: >
               {% for item in states | selectattr('entity_id', 'in', state_attr('group.dim_lights', 'entity_id')) | selectattr('state', 'equalto', 'on') -%}
               {% if not loop.first %},{% endif %}{{ item.entity_id }}
               {%- endfor %}
            #{{ states | selectattr('entity_id', 'in', state_attr('group.dim_lights', 'entity_id')) | selectattr('state', 'equalto', 'on') | map(attribute='entity_id')|list }}
        brightness: >
           {% if  now().hour < 5 %} 
              1
           {% elif now().hour >= 5 and now().hour < 7 %} 
              75
           {% elif now().hour >= 7 and now().hour < 20  %}
              255
           {% elif now().hour >= 20 and now().hour < 22  %}
              100
           {% elif now().hour >= 22 and now().hour < 23  %}
              30
           {% elif now().hour >= 23  %}
              1
           {% endif %}
        kelvin: '{% if now().hour >= 19 %}1700{% elif now().hour <= 7 %}1700{% else %}2500{% endif %}'
        transition: 120

- alias: 'Light4 - automation brightness triggered by swicth on'
  trigger:
    - platform: state
      entity_id: 
        - light.l_cucina_2
        - light.l_dressingroom
        - light.l_bagno
        - light.l_bedroom
      to: 'on'
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    - service: light.turn_on
      data_template:
        entity_id: "{{ trigger.entity_id }}"
        brightness: >
           {% if  now().hour < 6 %} 
              1
           {% elif now().hour >= 6 and now().hour < 7 %} 
              128
           {% elif now().hour >= 7 and now().hour < 20  %}
              255
           {% elif now().hour >= 20 and now().hour < 21  %}
              128
           {% elif now().hour >= 21 and now().hour < 23  %}
              30
           {% elif now().hour >= 23  %}
              1
           {% endif %}
        transition: 3

- alias: ' Light5 - automation light back home '
  trigger:
    - platform: state
      entity_id: group.family
      to: home
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    - service: light.turn_on
      entity_id: 
        - light.bagno
        - light.l_cucina_2
        - light.livingroom
        - light.entrance
   
   #wall led connection
- alias: 'Light7 - LED on wall '
  trigger:
    - platform: state 
      entity_id:
        - switch.sonoff_100056b199_3
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.sonoff
        
- alias: 'Light8 - LED on wall '
  trigger:
    - platform: state 
      entity_id:
        - switch.sonoff_100056b199_3
      to: 'off'
  action:
    - service: switch.turn_off
      entity_id: 
        - switch.sonoff
    
- alias: 'Light9 - LED on wall '
  trigger:
    - platform: state 
      entity_id:
        - switch.sonoff
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.sonoff_100056b199_3
        
- alias: 'Light10 - LED on wall '
  trigger:
    - platform: state 
      entity_id:
        - switch.sonoff
      to: 'off'
  action:
    - service: switch.turn_off
      entity_id: 
        - switch.sonoff_100056b199_3

- alias: 'Light15 - bathroom celing light '
  trigger:
    - platform: state
      entity_id: 
        - switch.sonoff_1000a53f4b
      to:
        - 'on'
        - 'off'
  condition:
    condition: state
    entity_id: light.l_bagno
    state: 'off'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.l_bagno
        brightness: >
           {% if  now().hour < 6 %} 
              1
           {% elif now().hour >= 6 and now().hour < 7 %} 
              128
           {% elif now().hour >= 7 and now().hour < 20  %}
              255
           {% elif now().hour >= 20 and now().hour < 21  %}
              128
           {% elif now().hour >= 21 and now().hour < 23  %}
              30
           {% elif now().hour >= 23  %}
              1
           {% endif %}
        transition: 4

- alias: 'Light16 - bathroom celing light '
  trigger:
    - platform: state
      entity_id: 
        - switch.sonoff_1000a53f4b
  condition:
    condition: state
    entity_id: light.l_bagno
    state: 'on'
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.l_bagno

- alias: 'Light17 - balcony south '
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.m_dressing
      to: 'on'
  condition:
    condition: state  # from sunset until sunrise
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    - service: switch.turn_on
      data_template:
        entity_id: switch.sonoff_1000a495ae

- alias: 'Light18 - balcony south '
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.m_dressing
      to: 'off'
      for:
       minutes: 3
  action:
    - service: switch.turn_off
      data_template:
        entity_id: switch.sonoff_1000a495ae