- id: 'Light1'
  alias: raise-up bathroom light at 100% with motion 
  trigger:
    platform: state
    entity_id: binary_sensor.m_bathroom
    to: 'on'
  condition:
    condition: time
    after: 07:00:00
    before: '19:00:00'
  action:
    service: light.turn_on
    entity_id: light.bagno
    data_template:
      transition: 4
      brightness: 255
      
- id: 'Light2'
  alias: raise-up bathroom light at 50% with motion 
  trigger:
    platform: state
    entity_id: binary_sensor.m_bathroom
    to: 'on'
  condition:
    condition: time
    after: '19:00:00'
  action:
    service: light.turn_on
    entity_id: light.bagno
    data_template:
      transition: 4
      brightness: 70
      
- id: 'Light3'
  alias: raise-down bathroom light 
  trigger:
    platform: state
    entity_id: binary_sensor.m_bathroom
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: time
    after: 07:00:00
    before: '19:00:00'
  action:
    service: light.turn_on
    entity_id: light.bagno
    data_template:
      transition: 90
      brightness: 10
      
- id: 'Light4'
  alias: raise-down bathroom light at (night)
  trigger:
    platform: state
    entity_id: binary_sensor.m_bathroom
    to: 'off'
    for:
      minutes: 10
  condition:
    condition: time
    after: '19:00:00'
  action:
    service: light.turn_on
    entity_id: light.bagno
    data_template:
      transition: 45
      brightness: 1

#Light Temperature by sunlight

- id: ' Light5'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  action:
    service: yeelight.set_color_temp_scene
    entity_id: group.rgb_lights
    data_template:
      kelvin: 1800
      brightness: 128


- id: ' Light6'
  trigger:
    platform: sun
    event: sunrise
    offset: "00:05:00"
  action:
    service: yeelight.set_color_temp_scene
    entity_id: group.rgb_lights
    data_template:
      kelvin: 3000
      brightness: 255
