- alias: 'Entrancelight - decoration auto brigthness'
  trigger:
    - platform: state
      entity_id: binary_sensor.input14 # livingroom door
    - platform: state
      entity_id: sensor.dark_outside 
    - platform: state
      entity_id: sensor.light_on_west
    - platform: state
      entity_id: binary_sensor.television
    - platform: state
      entity_id: sun.sun
    - platform: state
      entity_id: group.family
    - platform: time
      at: "21:30:00"
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
  action:
    - service: light.turn_on
      data_template:
        entity_id: 
           - light.shelly_shrgbw2_f4337c_3
        brightness_pct: >
                 {% if (states.binary_sensor.input14.state == 'on') 
                  and (states.sensor.dark_outside.state == 'False') 
                  and (states.sensor.light_on_west.state == 'false') %} 
                  80  
                 {% elif (states.binary_sensor.input14.state == 'on') 
                    and (states.sensor.dark_outside.state == 'False') 
                    and (states.sensor.light_on_west.state == 'true') %} 
                  100  
                 {% elif  (states.binary_sensor.input14.state == 'off') 
                     and (states.sun.sun.state == 'above_horizon')
                     and (states.sensor.light_on_west.state == 'true') %} 
                  75  
                 {% elif  (states.binary_sensor.input14.state == 'on') 
                     and (states.sun.sun.state == 'above_horizon') %} 
                 50  
                 {% elif  (states.sensor.dark_outside.state == 'True') 
                     and (states.sensor.light_on_west.state == 'false')
                     and (states.binary_sensor.television.state == 'Off') 
                     and (states.sun.sun.state == 'below_horizon') %} 
                  20  
                 {% elif  (states.binary_sensor.television.state == 'on') 
                    and (states.sun.sun.state == 'below_horizon') %} 
                  1  
                 {% elif  now().hour >= 21  %} 
                 1        
                 {% endif %}

- alias: 'Entrancelight - main '
  trigger:
    - platform: state 
      entity_id: switch.sonoff_1000a4166e
      to: 
        - 'off'
        - 'on'
  action:
    - service: light.toggle
      entity_id: 
        - light.shelly_shrgbw2_f4337c_4



