- alias: 'lightbathroom raise-up by motion '
  trigger:
    - platform: state
      entity_id: binary_sensor.m_bathroom
      to: 'on'
  action:
    service: light.turn_on
    entity_id: light.yeelight_l_ceiling
    data_template:
      brightness: >
           {% if  now().hour < 6 %} 
              70
           {% elif now().hour >= 6 and now().hour < 7 %} 
              128
           {% elif now().hour >= 7 and now().hour < 20  %}
              255
           {% elif now().hour >= 20 and now().hour < 22  %}
              128
           {% elif now().hour >= 22  %}
              70
           {% endif %}
      kelvin: '{% if now().hour >= 19 %}1700{% elif now().hour <= 7 %}1700{% else %}2500{% endif %}'
      transition: 4
   
- alias: 'lightbathroom raise-down with no-motion'
  trigger:
    platform: state
    entity_id: binary_sensor.m_bathroom
    to: 'off'
    for:
      minutes: 10
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
     - service: light.turn_on
       entity_id: light.yeelight_l_ceiling
       data_template:
         transition: 10
         brightness: 1
    - service: light.turn_off
      data_template:
        entity_id: light.l_bathroom_main
    - service: switch.turn_off
      entity_id: 
        - switch.sonoff_1000a5758e  




- alias: 'lightbathroom - celing light on'
  trigger:
    - platform: state
      entity_id: 
        - switch.sonoff_1000a53f4b
      to:
        - 'on'
        - 'off'
  condition:
    condition: state
    entity_id: light.l_bathroom_main
    state: 'off'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.l_bathroom_main
        brightness: >
           {% if  now().hour < 6 %} 
              1
           {% elif now().hour >= 6 and now().hour < 7 %} 
              128
           {% elif now().hour >= 7 and now().hour < 20  %}
              255
           {% elif now().hour >= 20 and now().hour < 21  %}
              128
           {% elif now().hour >= 21 and now().hour < 23  %}
              30
           {% elif now().hour >= 23  %}
              1
           {% endif %}
        transition: 4

- alias: 'lightbathroom - celing light off'
  trigger:
    - platform: state
      entity_id: 
        - switch.sonoff_1000a53f4b
  condition:
    condition: state
    entity_id: light.l_bathroom_main
    state: 'on'
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.l_bathroom_main


   



