- alias: 'Light1 - raise-up bathroom at 100% with motion '
  trigger:
    platform: state
    entity_id: binary_sensor.m_bathroom
    to: 'on'
  condition:
    condition: time
    after: 07:00:00
    before: '19:00:00'
  action:
    service: light.turn_on
    entity_id: light.bagno
    data_template:
      transition: 4
      brightness: 255
      
- alias: 'Light2 - raise-up bathroom at 50% with motion '
  trigger:
    platform: state
    entity_id: binary_sensor.m_bathroom
    to: 'on'
  condition:
    condition: time
    after: '19:00:00'
  action:
    service: light.turn_on
    entity_id: light.bagno
    data_template:
      transition: 4
      brightness: 70
      
- alias: 'Light3 - raise-down bathroom light'
  trigger:
    platform: state
    entity_id: binary_sensor.m_bathroom
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: time
    after: 07:00:00
    before: '19:00:00'
  action:
    service: light.turn_on
    entity_id: light.bagno
    data_template:
      transition: 90
      brightness: 10
      
- id: 'Light4 - raise-down bathroom light at (night)'
  trigger:
    platform: state
    entity_id: binary_sensor.m_bathroom
    to: 'off'
    for:
      minutes: 10
  condition:
    condition: time
    after: '19:00:00'
  action:
    service: light.turn_on
    entity_id: light.bagno
    data_template:
      transition: 45
      brightness: 1

#Light Temperature by sunlight

- alias: ' Light5 - automation color/brightness on fixed lights '
  trigger:
    - platform: state
      entity_id: group.family
      to: home
    - platform: time
      at: "08:00:01"
    - platform: time
      at: "19:00:01"
    - platform: time
      at: "20:00:01"
    - platform: sun
      event: sunset
      offset: "00:30:00"
    - platform: sun
      event: sunrise
      offset: "00:30:00"
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    - service: light.turn_on
      entity_id: 
        - light.entrance
        - light.livingroom 
        - light.bagno
        - light.l_cucina_2
      data_template:
        brightness: '{% if now().hour >= 19 %}30{% elif now().hour <= 8 %}30{% else %}255{% endif %}'
        kelvin: '{% if now().hour >= 19 %}1700{% elif now().hour <= 8 %}1700{% else %}3000{% endif %}'

- alias: 'Light6 - automation color/brightness triggered by swicth on'
  trigger:
    - platform: state
      entity_id: 
        - light.entrance
        - light.livingroom 
        - light.bagno
        - light.l_cucina_2
        - light.l_dressingroom
        - light.l_bagno
        - light.l_bedroom
      to: 'on'
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    - service: light.turn_on
      data_template:
        entity_id: "{{ trigger.entity_id }}"
        brightness: '{% if now().hour >= 19 %}30{% elif now().hour <= 8 %}30{% else %}255{% endif %}'
        kelvin: '{% if now().hour >= 19 %}1700{% elif now().hour <= 8 %}1700{% else %}3000{% endif %}'
  
   
    

