- alias: 'Speaker off on tv off '
  trigger:
    platform: state
    entity_id: binary_sensor.television
    to: 'off'
    for:
      minutes: 1
  action:
    - service: switch.turn_off
      entity_id: switch.sonoff_10008cbb1d_1