- alias: television mode
  trigger:
    - platform: numeric_state
      entity_id: 
        - sensor.pow2_power
      above: 20
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: time
      after: '21:00:00'
  action:
    - service: telegram_bot.send_message
      data_template:
        title: "television mode triggered"
        message: >
              at {{ now().strftime("%H:%M") }} 
    - service: input_select.select_option
      data:
        entity_id: input_select.living_room_sceene
        option: 'Tv'
    
# - alias: 'Speaker off on tv off '
#   trigger:
#     platform: state
#     entity_id: binary_sensor.television
#     to: 'off'
#     for:
#       minutes: 1
#   action:
#     - service: switch.turn_off
#       entity_id: switch.sonoff_10008cbb1d_1
