- alias: television mode
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.television
      to: 
        - 'on'
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: time
      after: '18:00:00'
  action:
    - service: telegram_bot.send_message
      data_template:
        title: "television mode triggered"
        message: >
              at {{ now().strftime("%H:%M") }} 
    - service: light.turn_off
      data_template:
        entity_id: 
        - light.yeelight_l_corner      #Livingroom cornerlamp
        - light.l_kitchen          #kitchen up lamp
        - light.yeelight_l_table      #Livingroom tv lamp
        - light.yeelight_l_ceiling
        - light.shelly_shrgbw2_f4337c_1 #Livingroom Led Warm
        - light.shelly_shrgbw2_f4337c_2 #Livingroom Led Natural
        - light.shelly_shrgbw2_f4337c_3 #Entance service Led
        - light.shelly_shrgbw2_f4337c_4 #Entance main Led
    - service: switch.turn_off
      data_template:
        entity_id: 
        - switch.sonoff_10008cbb1d_1 #
        - switch.sonoff_10008cbb1d_2 #
        - switch.sonoff_10008cbb1d_3 #
        - switch.sonoff_1000a54613 # kitchen LED
        - switch.sonoff # livingroom table LED
        - switch.sonoff_10009ce05a
    - service: automation.turn_off
      entity_id: automation.termo_deumidificate_full
    

