     
- alias: 'Termo crono'
  trigger:
    - platform: time_pattern
      minutes: "/10"
    - platform: state
      entity_id: group.family
      to: home
    - platform: homeassistant
      event: start
    - platform: state
      entity_id:
        - binary_sensor.w_livingroom
      to: 'off'
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    - service:  climate.set_hvac_mode
      data_template:
        entity_id: climate.riscaldamento
        hvac_mode: >
          {% if  now().strftime("%m") |int < 4 or now().strftime("%m") |int > 10 %} 
            heat
          {% else %} 
            off
          {% endif %}
    - service: climate.set_temperature
      data_template:
        entity_id: climate.riscaldamento
        temperature:  >
           {% if  now().hour < 7 %} 
              10
           {% elif now().hour >= 7 and now().hour < 9 %} 
              19
           {% elif now().hour >= 9 and now().hour < 18  %}
              18
           {% elif now().hour >= 18 and now().hour < 21  %}
              20
           {% elif now().hour >= 21 and now().hour < 23  %}
              19
           {% elif now().hour >= 23  %}
              10
           {% endif %}
        

- alias: 'Termo - manual request '
  trigger:
    platform: state
    entity_id: binary_sensor.sonoff_switch1_2
    to: 'on'
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.riscaldamento
        temperature: "{{ states.climate.riscaldamento.attributes.temperature |float +0.5 }}"

     
- alias: 'Termo - window open '
  trigger:
    platform: state
    entity_id:
      - binary_sensor.w_livingroom
    to: 'on'
    for:
      minutes: 3
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.riscaldamento
        temperature: 10