     
- alias: 'Termo crono'
  trigger:
    - platform: time_pattern
      minutes: 1
    - platform: state
      entity_id: group.family
      to: home
    - platform: homeassistant
      event: start
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.riscaldamento
        temperature:  >
           {% if  now().hour < 6 %} 
              15
           {% elif now().hour >= 6 and now().hour < 9 %} 
              20
           {% elif now().hour >= 9 and now().hour < 17  %}
              19
           {% elif now().hour >= 17 and now().hour < 21  %}
              20
           {% elif now().hour >= 21 and now().hour < 23  %}
              19.5
           {% elif now().hour >= 23  %}
              15
           {% endif %}
        

- alias: 'Termo - manual request '
  trigger:
    platform: state
    entity_id: binary_sensor.sonoff_switch1_2
    to: 'on'
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.riscaldamento
        temperature: "{{ states.climate.riscaldamento.attributes.temperature |float +0.5 }}"

     
       