- alias: hassio restart notification
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: telegram_bot.send_message
    data_template:
      title: Hassio Restarted
      message: >
        {% if  now().strftime("%m") |int < 4 or now().strftime("%m") |int > 10 %} 
          'winter season heater are: heat'
        {% else %} 
          'summer season heater: off'
        {% endif %}

- alias: avoid blackout notification
  trigger:
    - platform: state
      entity_id: 
        - switch.shelly_shsw_pm_b901af #Dishwasher
        - switch.shelly_shsw_pm_b906cb #General 10A
        - switch.shelly_shsw_pm_b911e9 #Oven
        - switch.shelly_shsw_pm_b91874 #Priority Line 10A
        - switch.shelly_shsw_pm_b9273a #Kitchen 1 /fridge
        - switch.shelly_shsw_pm_b9841d #Washing Machine
        - switch.shelly_shsw_pm_b984a1 #Bathroom socket
        - switch.shelly_shsw_pm_b98576 #General 16A
      to: 
        - 'off'
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
  action:
    - service: telegram_bot.send_message
      data_template:
        title: "Risk of blackout"
        message: 'at {{ now().strftime("%H:%M") }} shelly has stop {{trigger.from_state.attributes.friendly_name}} while was {{sensor.current_power}} W used'
