- alias: hassio restart notification
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: '00:00:30'
    - service: telegram_bot.send_message
      data_template:
        title: Hassio Restarted
        message: heater status {{ states.var.today_thermo_profile.state }}
    - service: automation.turn_on
      entity_id: automation.avoid_blackout_notification
      
      
- alias: hassio reload  automation
  trigger:
    platform: event
    event_type:
      - automation_reloaded
  action:
    - service: telegram_bot.send_message
      data_template:
        title: Automation Reloaded
        message: >
          at {{ now().strftime("%H:%M") }}  automation has been reloaded
    - delay: '00:00:30'
    - service: automation.turn_on
      entity_id: automation.avoid_blackout_notification
      
      



- alias: avoid blackout notification
  initial_state: False  # spenta quando Home Assistant si avvia
  trigger:
    - platform: state
      entity_id: 
        - switch.shelly_shsw_pm_b901af #Dishwasher
        - switch.shelly_shsw_pm_b906cb #General 10A
        - switch.shelly_shsw_pm_b911e9 #Oven
        - switch.shelly_shsw_pm_b9273a #Kitchen 1 /fridge
        - switch.shelly_shsw_pm_c4b0f4 #Washing Machine
        - switch.shelly_shsw_pm_b984a1 #Bathroom socket
        - switch.shelly_shsw_pm_84cca8aca64a #General 16A
      to: 
        - 'off'
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
  action:
    - delay: '00:00:10'
    - service: telegram_bot.send_message
      data_template:
        title: "Risk of blackout"
        message: >
              at {{ now().strftime("%H:%M") }} 
              shelly has stop {{trigger.from_state.attributes.friendly_name}}
              while was {{states.var.max_power_last3m.state}} W used
              the other device on its:
              {% if states.sensor.shelly_shsw_pm_b901af_current_consumption.state |int > 1000 %}
              Dishwasher
              {% elif states.sensor.shelly_shsw_pm_b906cb_current_consumption.state|int  > 1000 %}
              General 10A
              {% elif states.sensor.shelly_shsw_pm_b911e9_current_consumption.state |int > 1000 %}
              Oven
              {% elif states.sensor.shelly_shsw_pm_b9273a_current_consumption.state|int  > 1000 %}
              Boiler (water)
              {% elif states.sensor.shelly_shsw_pm_c4b0f4_current_consumption.state|int  > 1000 %}
              Washing Machine
              {% elif states.sensor.shelly_shsw_pm_b984a1_current_consumption.state|int  > 1000 %}
              phon
              {% elif states.sensor.shelly_shsw_pm_84cca8aca64a_current_consumption.state |int > 1000 %}
              General 16A
              {% endif %}
    - delay: '00:00:30'
    - service: telegram_bot.send_message
      data_template:
        title: "Risk of blackout"
        message: 'now that  {{trigger.from_state.attributes.friendly_name}} is stop  there is {{states.sensor.current_power.state}} W used'
    - service: automation.turn_on
      entity_id: automation.avoid_blackout_notification
    - service: automation.turn_on
      entity_id: automation.restart


- alias: restart
  initial_state: False  # spenta quando Home Assistant si avvia
  trigger:
    - platform: numeric_state
      entity_id: 
        - sensor.shelly_shsw_pm_b901af_current_consumption #Dishwasher
        - sensor.shelly_shsw_pm_b906cb_current_consumption #General 10A
        - sensor.shelly_shsw_pm_b911e9_current_consumption #Oven
        - sensor.shelly_shsw_pm_b9273a_current_consumption #Kitchen 1 /fridge
        - sensor.shelly_shsw_pm_c4b0f4_current_consumption #Washing Machine
        - sensor.shelly_shsw_pm_b984a1_current_consumption #Bathroom socket
        - sensor.shelly_shsw_pm_84cca8aca64a_current_consumption #General 16A
      below: 1500
      for:
        minutes: 3
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: numeric_state
      entity_id: sensor.current_power
      below: 1500
  action:
    - service: telegram_bot.send_message
      data_template:
        title: "Risk of blackout end"
        message: >
              at {{ now().strftime("%H:%M") }} 
              the current power is {{states.sensor.current_power.state}} W used
    - service: switch.turn_on
      entity_id: 
        - switch.shelly_shsw_pm_b901af #Dishwasher
        - switch.shelly_shsw_pm_b906cb #General 10A
        - switch.shelly_shsw_pm_b911e9 #Oven
        - switch.shelly_shsw_pm_b9273a #Kitchen 1 /fridge
        - switch.shelly_shsw_pm_c4b0f4 #Washing Machine
        - switch.shelly_shsw_pm_b984a1 #Bathroom socket
        - switch.shelly_shsw_pm_84cca8aca64a #General 16A
    - service: automation.turn_off
      entity_id: automation.restart