- alias: get_toyota_position
  trigger:
  - platform: state
    entity_id:
      - sensor.lat_toy
      - sensor.lon_toy
  - platform: homeassistant
    event: start
  action:
  - service: device_tracker.see
    data_template:
      dev_id: toy_location
      gps:
        - "{{ states('sensor.lat_toy') }}"
        - "{{ states('sensor.lon_toy') }}"
            
            
            
            
- alias: notification on movment of the car
  trigger:
    - platform: state
      entity_id: sensor.status_toy
  action:
    - wait_template: "{{state_attr('sensor.status_toy', 'last_changed')}}"
      timeout: "00:01:30"
    - service: telegram_bot.send_message
      data_template:
        title: Toyota {{trigger.to_state.state}}
        message: |
                {{state_attr('sensor.status_toy', 'last_changed')}} Toyota {{state_attr('sensor.status_toy', 'descr')}} 
                {{states.sensor.toy_street.state}} 